// lib/catalogModels.ts
// Data layer: category → models → variants
// Designed to be CMS-ready: all fields are plain data, no UI logic.

export interface ColorOption {
  name: string;
  hex: string;
  image?: string;
}

export interface CatalogVariant {
  id: string;
  name: string;
  subtitle?: string;
  patternCode?: string;
  image?: string;
  galleryImages?: string[];
  description: string;
  features: string[];
  suitableFor: string[];
  colorOptions: ColorOption[];
  materialOptions: string[];
  densityOptions: string[];
  sizeOptions: string[];
  brandingOptions: string[];
  placements: string[];
  configurableOptions: string[];
  sortOrder: number;
  isActive: boolean;
}

export interface CatalogModel {
  id: string;
  slug: string;
  name: string;
  patternCode?: string;
  shortDescription: string;
  fullDescription?: string;
  coverImage?: string;
  galleryImages?: string[];
  badges?: string[];
  suitableFor: string[];
  brandingOptions: string[];
  configurableOptions: string[];
  features: string[];
  variants: CatalogVariant[];
  sortOrder: number;
  isActive: boolean;
}

export interface CategoryModels {
  categorySlug: string;
  categoryTitle: string;
  categoryDescription?: string;
  sortOrder?: number;
  isActive?: boolean;
  models: CatalogModel[];
}

export type CatalogModelsMap = Record<string, CategoryModels>;

// ── Shared constants ──────────────────────────────────────────────────────────

const BASE_COLORS: ColorOption[] = [
  { name: 'Чёрный', hex: '#1a1a1a' },
  { name: 'Белый', hex: '#ffffff' },
  { name: 'Серый', hex: '#9ca3af' },
  { name: 'Тёмно-синий', hex: '#1e3a5f' },
  { name: 'Красный', hex: '#dc2626' },
  { name: 'Жёлтый', hex: '#f5c518' },
];

const STANDARD_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', 'Набор по ТЗ'];
const BAG_SIZES = ['Стандарт', 'Малый', 'Большой', 'По ТЗ'];
const JACKET_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'];

const T_BRANDING = ['Шелкография', 'DTF-печать', 'DTG-печать', 'Вышивка', 'Бирки'];
const HOODIE_BRANDING = ['Вышивка', 'DTF-печать', 'Шелкография', '3D-вышивка', 'Шевроны', 'Бирки'];
const POLO_BRANDING = ['Вышивка', 'Шелкография', 'Шевроны', 'Бирки'];
const JACKET_BRANDING = ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на элементах', 'Бирки'];
const BAG_BRANDING = ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки'];
const RAIN_BRANDING = ['Шелкография', 'Шевроны', 'DTF-печать'];

const T_PLACEMENTS = ['Грудь (центр)', 'Грудь (левая)', 'Спина (верх)', 'Спина (центр)', 'Рукав'];
const HOODIE_PLACEMENTS = ['Грудь', 'Спина', 'Капюшон', 'Рукав', 'Карман'];
const JACKET_PLACEMENTS = ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'];

// ── Data ──────────────────────────────────────────────────────────────────────

export const catalogModelsData: CatalogModelsMap = {
  futbolki: {
    categorySlug: 'futbolki',
    categoryTitle: 'Футболки',
    models: [
      {
        id: 'basic-tee',
        slug: 'basic-tee',
        name: 'Базовая футболка',
        shortDescription: 'Классическая промо-футболка из хлопка для мероприятий и командной одежды.',
        suitableFor: ['Промоакции и раздаточный мерч', 'Командная одежда', 'Мероприятия и выставки', 'Welcome-наборы'],
        brandingOptions: T_BRANDING,
        configurableOptions: ['Цвет из палитры', 'Размерная сетка', 'Место нанесения', 'Ткань и плотность'],
        features: ['Классический прямой крой', 'Круглая горловина рибана', 'Хлопок 100% или смеска'],
        variants: [
          {
            id: 'basic-160',
            name: 'Standard 160 г/м²',
            subtitle: 'Лёгкая промо-футболка',
            description: 'Лёгкая промо-футболка для массовых тиражей, акций и мероприятий. Хлопок 100%, плотность 160 г/м².',
            features: ['Хлопок 100%, 160 г/м²', 'Прямой крой', 'Круглая горловина рибана'],
            suitableFor: ['Промоакции', 'Раздаточный мерч', 'Массовые тиражи'],
            colorOptions: [...BASE_COLORS, { name: 'Бежевый', hex: '#d4b483' }],
            materialOptions: ['Хлопок 100%', 'Хлопок/полиэстер 50/50'],
            densityOptions: ['160 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет из палитры', 'Размерная сетка', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'basic-180',
            name: 'Classic 180 г/м²',
            subtitle: 'Классическая корпоративная',
            description: 'Классическая корпоративная футболка плотностью 180 г/м². Хороший баланс качества и цены.',
            features: ['Хлопок 100%, 180 г/м²', 'Прямой крой', 'Устойчива к стирке'],
            suitableFor: ['Командная одежда', 'Корпоративные подарки', 'Мероприятия'],
            colorOptions: [...BASE_COLORS, { name: 'Меланж серый', hex: '#c0bdb8' }],
            materialOptions: ['Хлопок 100%', 'Хлопок меланж'],
            densityOptions: ['180 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет из палитры', 'Размерная сетка', 'Место нанесения', 'Тип материала'],
            sortOrder: 2,
            isActive: true,
          },
          {
            id: 'basic-reinforced',
            name: 'Усиленная горловина',
            subtitle: 'Долговечная форма',
            description: 'Футболка с усиленной двойной горловиной из хлопок/лайкра. Хорошо держит форму после многократных стирок.',
            features: ['Усиленная двойная горловина', 'Плотная рибана', 'Хорошо держит форму'],
            suitableFor: ['Командная форма', 'Долгосрочная эксплуатация', 'Корпоративная одежда'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок/лайкра'],
            densityOptions: ['180 г/м²', '200 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
            sortOrder: 3,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'oversize-tee',
        slug: 'oversize-tee',
        name: 'Футболка оверсайз',
        shortDescription: 'Свободный крой для корпоративного мерча и бренд-магазинов.',
        suitableFor: ['Корпоративный мерч', 'Бренд-магазины', 'Lifestyle-коллекции'],
        brandingOptions: T_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Свободный оверсайз-крой', 'Удлинённая спинка', 'Хлопок 100%'],
        variants: [
          {
            id: 'oversize-200',
            name: 'Oversize Standard 200',
            subtitle: 'Базовый оверсайз',
            description: 'Базовый оверсайз с плотностью 200 г/м². Свободный крой, подходит для мерча и casual-коллекций.',
            features: ['Свободный крой', 'Хлопок 100%, 200 г/м²', 'Удлинённая спинка'],
            suitableFor: ['Корпоративный мерч', 'Casual-стиль', 'Бренд-коллекции'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Хлопок 100%', 'Хлопок меланж'],
            densityOptions: ['200 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'oversize-240',
            name: 'Oversize Heavy 240',
            subtitle: 'Плотный оверсайз',
            description: 'Плотный оверсайз 240 г/м² для премиального мерча. Отличная плотность и форма.',
            features: ['Хлопок 100%, 240 г/м²', 'Плотная структура', 'Свободный крой'],
            suitableFor: ['Премиальный мерч', 'Онбординг-наборы', 'Корпоративные подарки'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['240 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
          {
            id: 'oversize-washed',
            name: 'Oversize Washed',
            subtitle: 'Эффект состаривания',
            description: 'Оверсайз с эффектом washed — состаренная ткань с мягкой фактурой.',
            features: ['Эффект состаренной ткани', 'Мягкая фактура', 'Хлопок 100% washed'],
            suitableFor: ['Lifestyle-мерч', 'Бренд-магазины', 'Дизайн-коллекции'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Хлопок 100% (washed)'],
            densityOptions: ['220 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 3,
            isActive: true,
          },
          {
            id: 'oversize-premium',
            name: 'Oversize Premium',
            subtitle: 'Максимальная плотность',
            description: 'Премиальный оверсайз высокой плотности. Идеален для имиджевого мерча.',
            features: ['Максимальная плотность', 'Структурированная ткань', 'Оверсайз крой'],
            suitableFor: ['Имиджевый мерч', 'Корпоративные подарки', 'Бренд-магазины'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['240 г/м²', '260 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: ['Вышивка', 'DTF-печать', 'DTG-печать', 'Шелкография', 'Бирки'],
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Брендирование'],
            sortOrder: 4,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'polo-tee',
        slug: 'polo-tee',
        name: 'Футболка-поло',
        shortDescription: 'Поло из пике для деловой формы и корпоративных мероприятий.',
        suitableFor: ['Деловая форма', 'Корпоративные мероприятия', 'Представительская одежда'],
        brandingOptions: POLO_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Вышивка логотипа'],
        features: ['Пике-переплетение', 'Воротник-стойка', '2–3 пуговицы'],
        variants: [
          {
            id: 'polo-pique-200',
            name: 'Поло Piqué Classic',
            subtitle: 'Классическое поло',
            description: 'Классическое поло из пике 200 г/м². Стандарт корпоративной одежды.',
            features: ['Пике-переплетение', '2–3 пуговицы', 'Воротник рибана'],
            suitableFor: ['Деловая форма', 'Корпоративные мероприятия', 'Командная одежда'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Пике хлопок 100%', 'Пике хлопок/полиэстер'],
            densityOptions: ['200 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: POLO_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место вышивки'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'polo-pique-220',
            name: 'Поло Piqué Classic 220',
            subtitle: 'Плотное поло',
            description: 'Поло из пике 220 г/м² — более плотное и устойчивое к деформации.',
            features: ['Пике 220 г/м²', 'Плотная структура', 'Устойчиво к деформации'],
            suitableFor: ['Деловая форма', 'Регулярное использование', 'Корпоративная одежда'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Пике хлопок 100%'],
            densityOptions: ['220 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: POLO_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размерная сетка', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
          {
            id: 'polo-premium',
            name: 'Поло Premium',
            subtitle: 'Мерсеризованный хлопок',
            description: 'Премиальное поло из мерсеризованного хлопка с шёлковистой поверхностью.',
            features: ['Мерсеризация', 'Шёлковистая поверхность', 'Минимальная усадка'],
            suitableFor: ['Представительская одежда', 'Топ-менеджмент', 'Премиальные подарки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Пике мерсеризованный хлопок'],
            densityOptions: ['240 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: POLO_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размерная сетка', 'Вышивка', 'Шевроны'],
            sortOrder: 3,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 'premium-tee',
        slug: 'premium-tee',
        name: 'Премиальная плотная футболка',
        shortDescription: 'Высокая плотность для имиджевого мерча и корпоративных коллекций.',
        suitableFor: ['Имиджевый мерч', 'Корпоративные коллекции', 'Онбординг-наборы'],
        brandingOptions: T_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Повышенная плотность', 'Устойчива к деформации', 'Хлопок 100%'],
        variants: [
          {
            id: 'premium-220',
            name: 'Premium 220',
            subtitle: 'Плотная 220 г/м²',
            description: 'Плотная футболка 220 г/м² для имиджевого мерча. Хорошо держит форму.',
            features: ['Хлопок 100%, 220 г/м²', 'Структурированная ткань', 'Плотный крой'],
            suitableFor: ['Имиджевый мерч', 'Онбординг-наборы', 'Корпоративные подарки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['220 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'premium-260',
            name: 'Premium 260',
            subtitle: 'Максимальная плотность',
            description: 'Самая плотная футболка 260 г/м². Максимальная устойчивость к деформации.',
            features: ['Плотная ткань', 'Устойчива к деформации', 'Хлопок 100%, 260 г/м²'],
            suitableFor: ['Премиальный мерч', 'Корпоративные подарки', 'Бренд-коллекции'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['260 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 4,
        isActive: true,
      },
      {
        id: 'sport-tee',
        slug: 'sport-tee',
        name: 'Спортивная футболка',
        shortDescription: 'Влагоотводящие ткани для команд, спортивных событий и активного корпоратива.',
        suitableFor: ['Спортивные команды', 'Корпоративный спорт', 'Спортивные мероприятия'],
        brandingOptions: ['DTF-печать', 'Шелкография', 'Сублимация', 'Бирки'],
        configurableOptions: ['Цвет', 'Размерная сетка', 'Нанесение номера', 'Место логотипа'],
        features: ['Влагоотвод', 'Быстрое высыхание', 'Полиэстер 100%'],
        variants: [
          {
            id: 'sport-quick-dry',
            name: 'Quick Dry',
            subtitle: 'Влагоотводящая',
            description: 'Спортивная футболка с технологией Quick Dry. Быстро выводит влагу.',
            features: ['Влагоотвод', 'Быстрое высыхание', 'Лёгкая структура'],
            suitableFor: ['Спортивные мероприятия', 'Корпоративный спорт', 'Командные турниры'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Полиэстер 100%', 'Полиэстер/спандекс'],
            densityOptions: ['140 г/м²', '160 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: ['DTF-печать', 'Шелкография', 'Сублимация', 'Бирки'],
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'sport-raglan',
            name: 'Raglan',
            subtitle: 'Реглановый рукав',
            description: 'Спортивная футболка с реглановым рукавом для свободы движений.',
            features: ['Реглановый рукав', 'Свободная посадка', 'Смеска хлопок/полиэстер'],
            suitableFor: ['Командная форма', 'Спортивные тренировки', 'Активный отдых'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Смеска хлопок/полиэстер'],
            densityOptions: ['160 г/м²', '180 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: ['DTF-печать', 'Шелкография', 'Сублимация', 'Бирки'],
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
          {
            id: 'sport-team',
            name: 'Командная',
            subtitle: 'Для команд',
            description: 'Командная футболка с возможностью нанесения номеров и имён.',
            features: ['Нанесение номеров', 'Командная форма', 'Влагоотвод'],
            suitableFor: ['Спортивные команды', 'Корпоративные турниры', 'Командные мероприятия'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Полиэстер 100%', 'Смеска хлопок/полиэстер'],
            densityOptions: ['160 г/м²', '180 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: ['DTF-печать', 'Шелкография', 'Сублимация', 'Бирки'],
            placements: ['Грудь', 'Спина (номер)', 'Рукав'],
            configurableOptions: ['Цвет', 'Номера и имена', 'Размерная сетка', 'Место логотипа'],
            sortOrder: 3,
            isActive: true,
          },
        ],
        sortOrder: 5,
        isActive: true,
      },
    ],
  },

  hudi: {
    categorySlug: 'hudi',
    categoryTitle: 'Худи',
    models: [
      {
        id: 'basic-hoodie',
        slug: 'basic-hoodie',
        name: 'Базовое худи',
        shortDescription: 'Классическое корпоративное худи с капюшоном.',
        suitableFor: ['Командная одежда', 'Корпоративные подарки', 'Онбординг-наборы'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Капюшон с регулировкой', 'Боковые карманы', 'Начёс или петля'],
        variants: [
          {
            id: 'hoodie-classic-280',
            name: 'Classic 280 г/м²',
            subtitle: 'Базовая плотность',
            description: 'Базовое корпоративное худи плотностью 280 г/м².',
            features: ['Начёс хлопок, 280 г/м²', 'Капюшон с кулиской', 'Карман-кенгуру'],
            suitableFor: ['Командная одежда', 'Промо-мерч', 'Весна/осень'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
            densityOptions: ['280 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размерная сетка', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'hoodie-classic-320',
            name: 'Classic 320 г/м²',
            subtitle: 'Плотное базовое',
            description: 'Более плотное базовое худи 320 г/м² для прохладной погоды.',
            features: ['Начёс хлопок, 320 г/м²', 'Плотная структура', 'Тёплый капюшон'],
            suitableFor: ['Командная одежда', 'Осень/зима', 'Корпоративные подарки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок/полиэстер'],
            densityOptions: ['320 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размерная сетка', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'oversize-hoodie',
        slug: 'oversize-hoodie',
        name: 'Худи оверсайз',
        shortDescription: 'Свободный крой для мерча и lifestyle-коллекций.',
        suitableFor: ['Корпоративный мерч', 'Lifestyle-коллекции', 'Бренд-магазины'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Оверсайз крой', 'Увеличенный капюшон', 'Удлинённая спинка'],
        variants: [
          {
            id: 'hoodie-os-320',
            name: 'Oversize 320 г/м²',
            subtitle: 'Стандартный оверсайз',
            description: 'Оверсайз худи 320 г/м² со свободным кроем.',
            features: ['Петля хлопок, 320 г/м²', 'Оверсайз крой', 'Карман-кенгуру'],
            suitableFor: ['Корпоративный мерч', 'Lifestyle', 'Бренд-коллекции'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Петля хлопок', 'Начёс хлопок/полиэстер'],
            densityOptions: ['320 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'hoodie-os-360',
            name: 'Oversize 360 г/м²',
            subtitle: 'Тяжёлый оверсайз',
            description: 'Тяжёлое оверсайз худи 360 г/м² для зимнего мерча.',
            features: ['Плотная петля, 360 г/м²', 'Максимальная плотность', 'Тёплый объёмный капюшон'],
            suitableFor: ['Зимний мерч', 'Корпоративные подарки', 'Премиальные коллекции'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Петля хлопок'],
            densityOptions: ['360 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
          {
            id: 'hoodie-os-premium',
            name: 'Oversize Premium',
            subtitle: 'Премиальный оверсайз',
            description: 'Премиальное оверсайз худи с расширенными опциями брендирования.',
            features: ['340–360 г/м²', 'Премиальные материалы', 'Расширенное брендирование'],
            suitableFor: ['Имиджевый мерч', 'Топ-менеджмент', 'Онбординг-наборы'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Петля хлопок'],
            densityOptions: ['340 г/м²', '360 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: ['Вышивка', '3D-вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Тип брендирования'],
            sortOrder: 3,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'zip-hoodie',
        slug: 'zip-hoodie',
        name: 'Худи на молнии',
        shortDescription: 'Худи с центральной молнией — удобно снимать и надевать.',
        suitableFor: ['Командная форма', 'Корпоративная одежда', 'Спортивные мероприятия'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Молния по центру', 'Боковые карманы', 'Начёс или петля'],
        variants: [
          {
            id: 'hoodie-zip-basic',
            name: 'Zip Basic',
            subtitle: 'Базовая молния',
            description: 'Базовое худи на молнии 280–300 г/м² с боковыми карманами.',
            features: ['Молния по центру', 'Боковые карманы', 'Начёс хлопок'],
            suitableFor: ['Командная одежда', 'Корпоративная форма', 'Спорт'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
            densityOptions: ['280 г/м²', '300 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'hoodie-zip-premium',
            name: 'Zip Premium',
            subtitle: 'Премиальная молния',
            description: 'Премиальное худи на молнии 300–320 г/м² с качественной фурнитурой.',
            features: ['Качественная молния YKK', 'Плотный начёс', 'Двойной капюшон'],
            suitableFor: ['Премиальный мерч', 'Корпоративные подарки', 'Онбординг'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок', 'Петля хлопок'],
            densityOptions: ['300 г/м²', '320 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 'premium-hoodie',
        slug: 'premium-hoodie',
        name: 'Премиальное худи',
        shortDescription: 'Максимальная плотность и комфорт для имиджевых коллекций.',
        suitableFor: ['Имиджевый мерч', 'Онбординг-наборы', 'Корпоративные подарки'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Брендирование'],
        features: ['Двойной капюшон', 'Плотный футер', 'Премиальная фурнитура'],
        variants: [
          {
            id: 'hoodie-premium-futur',
            name: 'Premium Футер',
            subtitle: 'Двойной капюшон',
            description: 'Премиальное худи из футера с двойным капюшоном.',
            features: ['Двойной капюшон', 'Плотный футер', 'Усиленные швы'],
            suitableFor: ['Имиджевый мерч', 'Онбординг-наборы', 'Топ-менеджмент'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Футер хлопок'],
            densityOptions: ['320 г/м²', '360 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Брендирование'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'hoodie-premium-naches',
            name: 'Premium с начёсом',
            subtitle: 'Мягкий начёс',
            description: 'Премиальное худи с мягким начёсом внутри для максимального комфорта.',
            features: ['Мягкий начёс внутри', 'Хлопок 320 г/м²', 'Усиленные швы'],
            suitableFor: ['Корпоративные подарки', 'Зимний мерч', 'Welcome-наборы'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Трёхнитка с начёсом'],
            densityOptions: ['320 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 4,
        isActive: true,
      },
      {
        id: 'naches-hoodie',
        slug: 'naches-hoodie',
        name: 'Худи с начёсом',
        shortDescription: 'Тёплое худи с флисовым начёсом для холодных сезонов.',
        suitableFor: ['Зимняя команда', 'Корпоративные подарки', 'Тёплая одежда'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Начёс внутри', 'Тёплый капюшон', 'Трёхнитка'],
        variants: [
          {
            id: 'hoodie-naches-280',
            name: 'Начёс 280 г/м²',
            subtitle: 'Лёгкий начёс',
            description: 'Тёплое худи с начёсом 280 г/м². Для межсезонья.',
            features: ['Трёхнитка с начёсом, 280 г/м²', 'Мягкий внутренний слой', 'Капюшон с кулиской'],
            suitableFor: ['Весна/осень', 'Командная форма', 'Промо-мерч'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Трёхнитка с начёсом'],
            densityOptions: ['280 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'hoodie-naches-320',
            name: 'Начёс 320 г/м²',
            subtitle: 'Плотный начёс',
            description: 'Тёплое худи с плотным начёсом 320 г/м² для зимы.',
            features: ['Трёхнитка с начёсом, 320 г/м²', 'Максимальное тепло', 'Плотный капюшон'],
            suitableFor: ['Зима', 'Корпоративные подарки', 'Тёплые наборы'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Трёхнитка с начёсом'],
            densityOptions: ['320 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 5,
        isActive: true,
      },
    ],
  },

  svitshoty: {
    categorySlug: 'svitshoty',
    categoryTitle: 'Свитшоты',
    models: [
      {
        id: 'basic-sweat',
        slug: 'basic-sweat',
        name: 'Базовый свитшот',
        shortDescription: 'Классический свитшот без капюшона для корпоративной одежды.',
        suitableFor: ['Командная одежда', 'Корпоративный мерч', 'Онбординг-наборы'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Без капюшона', 'Манжеты рибана', 'Начёс или петля'],
        variants: [
          {
            id: 'sweat-260',
            name: 'Classic 260 г/м²',
            subtitle: 'Лёгкий свитшот',
            description: 'Лёгкий свитшот 260 г/м² для весны и осени.',
            features: ['Начёс хлопок, 260 г/м²', 'Манжеты рибана', 'Без капюшона'],
            suitableFor: ['Весна/осень', 'Командная одежда', 'Промо-мерч'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
            densityOptions: ['260 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'sweat-300',
            name: 'Classic 300 г/м²',
            subtitle: 'Плотный свитшот',
            description: 'Плотный свитшот 300 г/м² для прохладного сезона.',
            features: ['Начёс хлопок, 300 г/м²', 'Плотная структура', 'Манжеты рибана'],
            suitableFor: ['Осень/зима', 'Корпоративные подарки', 'Командная форма'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок/полиэстер'],
            densityOptions: ['300 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'oversize-sweat',
        slug: 'oversize-sweat',
        name: 'Свитшот оверсайз',
        shortDescription: 'Свободный крой свитшота для lifestyle-мерча.',
        suitableFor: ['Lifestyle-мерч', 'Бренд-коллекции', 'Корпоративный мерч'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Оверсайз крой', 'Удлинённый силуэт', 'Свободный фасон'],
        variants: [
          {
            id: 'sweat-os-280',
            name: 'Oversize 280 г/м²',
            subtitle: 'Стандартный оверсайз',
            description: 'Оверсайз свитшот 280 г/м² со свободным кроем.',
            features: ['Оверсайз крой, 280 г/м²', 'Удлинённая спинка', 'Манжеты рибана'],
            suitableFor: ['Lifestyle-мерч', 'Casual', 'Бренд-коллекции'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок', 'Петля хлопок'],
            densityOptions: ['280 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'sweat-os-320',
            name: 'Oversize 320 г/м²',
            subtitle: 'Плотный оверсайз',
            description: 'Плотный оверсайз свитшот 320 г/м².',
            features: ['Плотная структура, 320 г/м²', 'Оверсайз крой', 'Усиленные швы'],
            suitableFor: ['Зимний мерч', 'Корпоративные подарки', 'Премиальные коллекции'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Начёс хлопок/полиэстер'],
            densityOptions: ['320 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'premium-sweat',
        slug: 'premium-sweat',
        name: 'Премиальный свитшот',
        shortDescription: 'Высокая плотность и качество для имиджевых коллекций.',
        suitableFor: ['Имиджевый мерч', 'Онбординг-наборы', 'Корпоративные подарки'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Брендирование'],
        features: ['Футер хлопок', 'Максимальная плотность', 'Усиленные швы'],
        variants: [
          {
            id: 'sweat-premium-340',
            name: 'Premium 340 г/м²',
            subtitle: 'Премиум футер',
            description: 'Премиальный свитшот из футера 340 г/м².',
            features: ['Футер хлопок, 340 г/м²', 'Структурированная ткань', 'Манжеты рибана'],
            suitableFor: ['Имиджевый мерч', 'Корпоративные подарки', 'Онбординг'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Футер хлопок'],
            densityOptions: ['340 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Брендирование'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'sweat-premium-360',
            name: 'Premium 360 г/м²',
            subtitle: 'Максимальная плотность',
            description: 'Максимально плотный премиальный свитшот 360 г/м².',
            features: ['Футер хлопок, 360 г/м²', 'Максимальное качество', 'Долговечность'],
            suitableFor: ['Имиджевый мерч', 'Топ-менеджмент', 'Корпоративные наборы'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Футер хлопок'],
            densityOptions: ['360 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Брендирование'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 'naches-sweat',
        slug: 'naches-sweat',
        name: 'Свитшот с начёсом',
        shortDescription: 'Тёплый свитшот с мягким начёсом для холодного сезона.',
        suitableFor: ['Зимний мерч', 'Тёплые наборы', 'Корпоративные подарки'],
        brandingOptions: HOODIE_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Мягкий начёс', 'Трёхнитка', 'Тепло и комфорт'],
        variants: [
          {
            id: 'sweat-naches-280',
            name: 'Начёс 280 г/м²',
            subtitle: 'Лёгкий начёс',
            description: 'Свитшот с начёсом 280 г/м² для межсезонья.',
            features: ['Трёхнитка с начёсом, 280 г/м²', 'Мягкий внутренний слой', 'Без капюшона'],
            suitableFor: ['Весна/осень', 'Командная одежда', 'Мерч'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Трёхнитка с начёсом'],
            densityOptions: ['280 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'sweat-naches-300',
            name: 'Начёс 300 г/м²',
            subtitle: 'Плотный начёс',
            description: 'Плотный свитшот с начёсом 300 г/м² для зимнего сезона.',
            features: ['Трёхнитка с начёсом, 300 г/м²', 'Плотная структура', 'Максимальное тепло'],
            suitableFor: ['Зима', 'Корпоративные подарки', 'Тёплые наборы'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Трёхнитка с начёсом'],
            densityOptions: ['300 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: HOODIE_BRANDING,
            placements: HOODIE_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 4,
        isActive: true,
      },
    ],
  },

  longslivy: {
    categorySlug: 'longslivy',
    categoryTitle: 'Лонгсливы',
    models: [
      {
        id: 'basic-ls',
        slug: 'basic-ls',
        name: 'Базовый лонгслив',
        shortDescription: 'Классический лонгслив с длинным рукавом из хлопка.',
        suitableFor: ['Командная одежда', 'Промо-мерч', 'Демисезонная одежда'],
        brandingOptions: T_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Длинный рукав', 'Хлопок 100%', 'Прямой крой'],
        variants: [
          {
            id: 'ls-160',
            name: 'Standard 160 г/м²',
            subtitle: 'Лёгкий лонгслив',
            description: 'Лёгкий лонгслив 160 г/м² для промо и мерча.',
            features: ['Хлопок 100%, 160 г/м²', 'Длинный рукав', 'Прямой крой'],
            suitableFor: ['Промоакции', 'Раздаточный мерч', 'Весна'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['160 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'ls-180',
            name: 'Standard 180 г/м²',
            subtitle: 'Классический лонгслив',
            description: 'Классический лонгслив 180 г/м².',
            features: ['Хлопок 100%, 180 г/м²', 'Длинный рукав', 'Манжеты рибана'],
            suitableFor: ['Командная одежда', 'Корпоративные подарки', 'Демисезон'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%', 'Хлопок меланж'],
            densityOptions: ['180 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Материал', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'oversize-ls',
        slug: 'oversize-ls',
        name: 'Оверсайз лонгслив',
        shortDescription: 'Оверсайз лонгслив для lifestyle-мерча.',
        suitableFor: ['Lifestyle-мерч', 'Бренд-коллекции', 'Casual'],
        brandingOptions: T_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Свободный крой', 'Удлинённые рукава', 'Оверсайз силуэт'],
        variants: [
          {
            id: 'ls-os-180',
            name: 'Oversize 180',
            subtitle: 'Базовый оверсайз',
            description: 'Оверсайз лонгслив 180–200 г/м² со свободным кроем.',
            features: ['Оверсайз крой', 'Свободные рукава', 'Хлопок 100%'],
            suitableFor: ['Lifestyle', 'Casual-мерч', 'Бренд-коллекции'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['180 г/м²', '200 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Плотность', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'ls-os-220',
            name: 'Oversize Premium 220',
            subtitle: 'Плотный оверсайз',
            description: 'Плотный оверсайз лонгслив 220 г/м² для премиального мерча.',
            features: ['Плотный хлопок, 220 г/м²', 'Оверсайз крой', 'Усиленные швы'],
            suitableFor: ['Премиальный мерч', 'Корпоративные подарки', 'Имиджевые коллекции'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['220 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'premium-ls',
        slug: 'premium-ls',
        name: 'Плотный премиальный лонгслив',
        shortDescription: 'Высокая плотность для имиджевых коллекций и командной формы.',
        suitableFor: ['Имиджевый мерч', 'Командная форма', 'Корпоративные подарки'],
        brandingOptions: T_BRANDING,
        configurableOptions: ['Цвет', 'Плотность', 'Размерная сетка', 'Место нанесения'],
        features: ['Высокая плотность', 'Манжеты рибана', 'Устойчивость к деформации'],
        variants: [
          {
            id: 'ls-premium-220',
            name: 'Premium 220 г/м²',
            subtitle: 'Плотный лонгслив',
            description: 'Плотный лонгслив 220 г/м² для корпоративных коллекций.',
            features: ['Хлопок 100%, 220 г/м²', 'Манжеты рибана', 'Плотная структура'],
            suitableFor: ['Корпоративные подарки', 'Командная форма', 'Имиджевый мерч'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['220 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'ls-premium-240',
            name: 'Premium 240 г/м²',
            subtitle: 'Максимальная плотность',
            description: 'Максимально плотный лонгслив 240 г/м² для имиджевого мерча.',
            features: ['Хлопок 100%, 240 г/м²', 'Максимальная плотность', 'Долговечность'],
            suitableFor: ['Имиджевый мерч', 'Топ-менеджмент', 'Онбординг-наборы'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок 100%'],
            densityOptions: ['240 г/м²'],
            sizeOptions: STANDARD_SIZES,
            brandingOptions: T_BRANDING,
            placements: T_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
    ],
  },

  sumki: {
    categorySlug: 'sumki',
    categoryTitle: 'Сумки',
    models: [
      {
        id: 'shopper-basic',
        slug: 'shopper-basic',
        name: 'Шоппер базовый',
        shortDescription: 'Хлопковый шоппер для промоакций и корпоративных подарков.',
        suitableFor: ['Промоакции', 'Корпоративные подарки', 'Раздаточный мерч'],
        brandingOptions: BAG_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размер', 'Место нанесения'],
        features: ['Хлопок 100%', 'Длинные ручки', 'Экологичный материал'],
        variants: [
          {
            id: 'shopper-canvas-220',
            name: 'Холст 220 г/м²',
            subtitle: 'Стандартный хлопок',
            description: 'Хлопковый шоппер из холста 220 г/м² — стандарт для промоакций.',
            features: ['Хлопок 220 г/м²', 'Длинные ручки', 'Плоское дно'],
            suitableFor: ['Промоакции', 'Раздаточный мерч', 'Корпоративные подарки'],
            colorOptions: [...BASE_COLORS, { name: 'Бежевый', hex: '#d4b483' }],
            materialOptions: ['Хлопок 220 г/м²'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'shopper-canvas-280',
            name: 'Холст плотный 280 г/м²',
            subtitle: 'Плотный хлопок',
            description: 'Плотный хлопковый шоппер 280 г/м² повышенной прочности.',
            features: ['Хлопок 280 г/м²', 'Усиленные швы', 'Долговечность'],
            suitableFor: ['Корпоративные подарки', 'Регулярное использование', 'Промо'],
            colorOptions: [...BASE_COLORS, { name: 'Бежевый', hex: '#d4b483' }],
            materialOptions: ['Хлопок 280 г/м²'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'shopper-heavy',
        slug: 'shopper-heavy',
        name: 'Шоппер плотный',
        shortDescription: 'Прочный шоппер из оксфорда для многоразового использования.',
        suitableFor: ['Корпоративные подарки', 'Регулярное использование', 'Брендинг'],
        brandingOptions: BAG_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размер', 'Место нанесения'],
        features: ['Оксфорд', 'Усиленное дно', 'Высокая прочность'],
        variants: [
          {
            id: 'shopper-oxford',
            name: 'Оксфорд',
            subtitle: 'Прочный оксфорд',
            description: 'Шоппер из оксфорда с высокой прочностью.',
            features: ['Оксфорд 210D или 420D', 'Усиленные ручки', 'Водоотталкивающий'],
            suitableFor: ['Корпоративные подарки', 'Регулярное использование', 'Выставки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Оксфорд 210D', 'Оксфорд 420D'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Плотность ткани', 'Размер', 'Нанесение'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'shopper-bottom',
            name: 'С укреплённым дном',
            subtitle: 'Укреплённое дно',
            description: 'Шоппер с укреплённым дном из комбинации хлопка и оксфорда.',
            features: ['Укреплённое дно', 'Комбинированный материал', 'Повышенная прочность'],
            suitableFor: ['Регулярное использование', 'Корпоративные подарки', 'Тяжёлые нагрузки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок + оксфорд дно'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'bag-long-handles',
        slug: 'bag-long-handles',
        name: 'Сумка с длинными ручками',
        shortDescription: 'Сумка на плечо с длинными ручками для удобства.',
        suitableFor: ['Повседневное использование', 'Корпоративные подарки', 'Промо'],
        brandingOptions: BAG_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Длина ручек', 'Нанесение'],
        features: ['Длинные ручки', 'Вместительный объём', 'На плечо'],
        variants: [
          {
            id: 'bag-cotton-long',
            name: 'Хлопок, длинные ручки',
            subtitle: 'Хлопок на плечо',
            description: 'Хлопковая сумка на плечо с длинными ручками.',
            features: ['Хлопок 220 г/м²', 'Длинные ручки', 'На плечо'],
            suitableFor: ['Повседневное использование', 'Промо', 'Корпоративные подарки'],
            colorOptions: [...BASE_COLORS, { name: 'Бежевый', hex: '#d4b483' }],
            materialOptions: ['Хлопок 220 г/м²'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'bag-oxford-long',
            name: 'Оксфорд, длинные ручки',
            subtitle: 'Оксфорд на плечо',
            description: 'Сумка из оксфорда на плечо с длинными ручками.',
            features: ['Оксфорд 210D', 'Длинные ручки', 'Водоотталкивающий'],
            suitableFor: ['Регулярное использование', 'Корпоративные подарки', 'Выставки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Оксфорд'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 'bag-zip',
        slug: 'bag-zip',
        name: 'Сумка с молнией',
        shortDescription: 'Закрытая сумка с молнией для надёжного хранения.',
        suitableFor: ['Корпоративные подарки', 'Командировки', 'Повседневное использование'],
        brandingOptions: BAG_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размер', 'Нанесение'],
        features: ['Молния', 'Закрытый отсек', 'Надёжное хранение'],
        variants: [
          {
            id: 'bag-zip-cotton',
            name: 'Хлопок с молнией',
            subtitle: 'Хлопок + молния',
            description: 'Хлопковая сумка с молнией для надёжного хранения.',
            features: ['Хлопок или нейлон', 'Молния', 'Закрытый отсек'],
            suitableFor: ['Корпоративные подарки', 'Повседневное использование', 'Спорт'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Хлопок', 'Нейлон'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Материал', 'Размер', 'Нанесение'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'bag-zip-oxford',
            name: 'Оксфорд с молнией',
            subtitle: 'Прочная с молнией',
            description: 'Прочная сумка из оксфорда с молнией.',
            features: ['Оксфорд 210D', 'Молния', 'Водоотталкивающий'],
            suitableFor: ['Корпоративные подарки', 'Командировки', 'Регулярное использование'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Оксфорд 210D'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона', 'Задняя сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 4,
        isActive: true,
      },
      {
        id: 'backpack-drawstring',
        slug: 'backpack-drawstring',
        name: 'Рюкзак-мешок',
        shortDescription: 'Лёгкий рюкзак-мешок на затяжке для спорта и промо.',
        suitableFor: ['Спортивные мероприятия', 'Промо', 'Корпоративные подарки'],
        brandingOptions: BAG_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размер', 'Нанесение'],
        features: ['Затяжка', 'Лёгкий', 'Компактный'],
        variants: [
          {
            id: 'bp-cotton',
            name: 'Хлопковый мешок',
            subtitle: 'Хлопок на затяжке',
            description: 'Лёгкий хлопковый рюкзак-мешок на затяжке.',
            features: ['Хлопок 100%', 'Затяжка', 'Экологичный'],
            suitableFor: ['Спортивные мероприятия', 'Промо', 'Раздаточный мерч'],
            colorOptions: [...BASE_COLORS, { name: 'Бежевый', hex: '#d4b483' }],
            materialOptions: ['Хлопок'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'bp-oxford',
            name: 'Оксфорд мешок',
            subtitle: 'Оксфорд на затяжке',
            description: 'Прочный рюкзак-мешок из оксфорда.',
            features: ['Оксфорд 210D', 'Затяжка', 'Водоотталкивающий'],
            suitableFor: ['Спортивные мероприятия', 'Активный отдых', 'Промо'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Оксфорд'],
            densityOptions: [],
            sizeOptions: BAG_SIZES,
            brandingOptions: BAG_BRANDING,
            placements: ['Лицевая сторона'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 5,
        isActive: true,
      },
    ],
  },

  zhiletki: {
    categorySlug: 'zhiletki',
    categoryTitle: 'Жилетки',
    models: [
      {
        id: 'insulated-vest',
        slug: 'insulated-vest',
        name: 'Утеплённая жилетка',
        shortDescription: 'Тёплая жилетка с утеплителем для холодного сезона.',
        suitableFor: ['Зимняя корпоративная форма', 'Outdoor-мероприятия', 'Тёплые подарки'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место нанесения'],
        features: ['Утеплитель', 'Безрукавный крой', 'Молния или кнопки'],
        variants: [
          {
            id: 'vest-ins-oxford',
            name: 'Утеплённая оксфорд',
            subtitle: 'Оксфорд + утеплитель',
            description: 'Жилетка из оксфорда с утеплителем.',
            features: ['Оксфорд + утеплитель', 'Молния', 'Боковые карманы'],
            suitableFor: ['Зимняя форма', 'Outdoor', 'Корпоративные подарки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Оксфорд + утеплитель'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'vest-ins-nylon',
            name: 'Утеплённая нейлон',
            subtitle: 'Нейлон + синтепон',
            description: 'Лёгкая нейлоновая жилетка с синтепоновым утеплителем.',
            features: ['Нейлон + синтепон', 'Лёгкая', 'Водоотталкивающая'],
            suitableFor: ['Демисезонная форма', 'Активный outdoor', 'Корпоративные подарки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Нейлон + синтепон'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'light-vest',
        slug: 'light-vest',
        name: 'Лёгкая жилетка',
        shortDescription: 'Лёгкая жилетка для лета и промо-мероприятий.',
        suitableFor: ['Летняя корпоративная форма', 'Промо-мероприятия', 'Выставки'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место нанесения'],
        features: ['Лёгкая конструкция', 'Сетчатая подкладка', 'Молния'],
        variants: [
          {
            id: 'vest-light-promo',
            name: 'Промо-жилетка',
            subtitle: 'Лёгкая промо',
            description: 'Лёгкая промо-жилетка из полиэстера с сетчатой структурой.',
            features: ['Полиэстер сетка', 'Лёгкая', 'Промо'],
            suitableFor: ['Промо-мероприятия', 'Выставки', 'Летняя форма'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Полиэстер сетка'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'vest-light-signal',
            name: 'Сигнальная',
            subtitle: 'Сигнальный цвет',
            description: 'Жилетка из сигнального полиэстера повышенной видимости.',
            features: ['Полиэстер сигнальный', 'Повышенная видимость', 'ГОСТ-совместимая'],
            suitableFor: ['Технический персонал', 'Outdoor-работы', 'Строительство'],
            colorOptions: [
              { name: 'Оранжевый', hex: '#f97316' },
              { name: 'Жёлтый сигнальный', hex: '#f5c518' },
              ...BASE_COLORS,
            ],
            materialOptions: ['Полиэстер сигнальный'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'corporate-vest',
        slug: 'corporate-vest',
        name: 'Корпоративная жилетка',
        shortDescription: 'Деловая жилетка для корпоративной формы и мероприятий.',
        suitableFor: ['Корпоративная форма', 'Деловые мероприятия', 'Представительская одежда'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Вышивка'],
        features: ['Деловой стиль', 'Оксфорд 420D', 'Несколько карманов'],
        variants: [
          {
            id: 'vest-corp-oxford',
            name: 'Корпоративная оксфорд',
            subtitle: 'Деловой стиль',
            description: 'Корпоративная жилетка из оксфорда 420D.',
            features: ['Оксфорд 420D', 'Деловой фасон', 'Боковые карманы'],
            suitableFor: ['Корпоративная форма', 'Деловые мероприятия', 'Выставки'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Оксфорд 420D'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Вышивка', 'Шевроны'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'vest-corp-pockets',
            name: 'С множеством карманов',
            subtitle: 'Функциональная',
            description: 'Корпоративная жилетка с множеством карманов из оксфорда и флиса.',
            features: ['Множество карманов', 'Оксфорд 420D + флис', 'Функциональность'],
            suitableFor: ['Технический персонал', 'Промо-команда', 'Корпоративная форма'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Оксфорд 420D + флис'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 'softshell-vest',
        slug: 'softshell-vest',
        name: 'Жилетка Softshell',
        shortDescription: 'Жилетка Softshell с защитой от ветра и влаги.',
        suitableFor: ['Активный outdoor', 'Демисезонная форма', 'Корпоративные подарки'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место нанесения'],
        features: ['Softshell', 'Ветро- и влагозащита', 'Стрейч'],
        variants: [
          {
            id: 'vest-ss-basic',
            name: 'Softshell Basic',
            subtitle: 'Базовый Softshell',
            description: 'Базовая жилетка Softshell с защитой от ветра.',
            features: ['Softshell', 'Ветрозащита', 'Влагоотталкивающий'],
            suitableFor: ['Активный outdoor', 'Корпоративная форма', 'Демисезон'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Softshell'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'vest-ss-stretch',
            name: 'Softshell Stretch',
            subtitle: 'Эластичный Softshell',
            description: 'Жилетка Softshell со стрейч-тканью для свободы движений.',
            features: ['Softshell Stretch', '4-way stretch', 'Свобода движений'],
            suitableFor: ['Активный спорт', 'Outdoor-мероприятия', 'Корпоративная форма'],
            colorOptions: [
              ...BASE_COLORS,
              { name: 'Графит', hex: '#374151' },
              { name: 'Хаки', hex: '#556b2f' },
            ],
            materialOptions: ['Softshell Stretch'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 4,
        isActive: true,
      },
    ],
  },

  kurtki: {
    categorySlug: 'kurtki',
    categoryTitle: 'Куртки',
    models: [
      {
        id: 'windbreaker',
        slug: 'windbreaker',
        name: 'Ветровка',
        shortDescription: 'Лёгкая ветровка для защиты от ветра и лёгкого дождя.',
        suitableFor: ['Спортивные мероприятия', 'Корпоративная форма', 'Демисезон'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место нанесения'],
        features: ['Ветрозащита', 'Лёгкий вес', 'Нейлон или таффета'],
        variants: [
          {
            id: 'wind-taffeta',
            name: 'Ветровка Таффета',
            subtitle: 'Лёгкая таффета',
            description: 'Лёгкая ветровка из таффеты или нейлона.',
            features: ['Таффета или нейлон', 'Лёгкий вес', 'Упаковывается в карман'],
            suitableFor: ['Спортивные мероприятия', 'Корпоративная форма', 'Промо'],
            colorOptions: [
              ...BASE_COLORS,
              { name: 'Графит', hex: '#374151' },
              { name: 'Хаки', hex: '#556b2f' },
              { name: 'Оранжевый', hex: '#f97316' },
            ],
            materialOptions: ['Таффета', 'Нейлон'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Материал', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'wind-premium',
            name: 'Ветровка Premium',
            subtitle: 'Премиальный нейлон',
            description: 'Премиальная ветровка из нейлона с улучшенными характеристиками.',
            features: ['Нейлон Premium', 'Усиленные молнии', 'Проклеенные швы'],
            suitableFor: ['Имиджевая форма', 'Корпоративные подарки', 'Спорт'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Нейлон Premium'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'softshell-jacket',
        slug: 'softshell-jacket',
        name: 'Куртка Softshell',
        shortDescription: 'Куртка Softshell с защитой от ветра, влаги и стрейч-кроем.',
        suitableFor: ['Корпоративная форма', 'Active outdoor', 'Демисезон'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место нанесения'],
        features: ['3 слоя Softshell', 'Ветро- и влагозащита', 'Стрейч-крой'],
        variants: [
          {
            id: 'jacket-ss-basic',
            name: 'Softshell 3 слоя',
            subtitle: 'Трёхслойный Softshell',
            description: 'Куртка Softshell трёхслойная с полной ветро- и влагозащитой.',
            features: ['Softshell 3 слоя', 'Полная защита', 'Дышащий материал'],
            suitableFor: ['Корпоративная форма', 'Active outdoor', 'Осень/зима'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Softshell 3 слоя'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'jacket-ss-stretch',
            name: 'Softshell Stretch',
            subtitle: 'Эластичный Softshell',
            description: 'Куртка Softshell со стрейч-тканью 4-way для полной свободы движений.',
            features: ['Softshell Stretch 4-way', 'Максимальный стрейч', 'Свобода движений'],
            suitableFor: ['Активный спорт', 'Outdoor-мероприятия', 'Корпоративная форма'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Softshell Stretch 4-way'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'insulated-jacket',
        slug: 'insulated-jacket',
        name: 'Утеплённая куртка',
        shortDescription: 'Зимняя куртка с синтепоновым утеплением для холодных сезонов.',
        suitableFor: ['Зимняя корпоративная форма', 'Outdoor-работы', 'Корпоративные подарки'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Утеплитель', 'Размерная сетка', 'Место нанесения'],
        features: ['Синтепоновый утеплитель', 'Оксфорд верх', 'Зимний крой'],
        variants: [
          {
            id: 'jacket-ins-200',
            name: 'Утеплитель 200 г',
            subtitle: 'Демисезонная',
            description: 'Куртка с синтепоновым утеплителем 200 г/м² для демисезона.',
            features: ['Оксфорд + синтепон 200г', 'Демисезонная', 'Водоотталкивающий верх'],
            suitableFor: ['Демисезонная форма', 'Outdoor-работы', 'Корпоративные подарки'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Оксфорд + синтепон 200г'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'jacket-winter',
            name: 'Зимняя 300 г',
            subtitle: 'Зимняя куртка',
            description: 'Зимняя куртка с утеплителем 300 г/м² для суровых условий.',
            features: ['Оксфорд + синтепон 300г', 'Зимняя', 'Максимальное утепление'],
            suitableFor: ['Зимняя форма', 'Холодный климат', 'Корпоративные подарки'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Оксфорд + синтепон 300г'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 'demi-jacket',
        slug: 'demi-jacket',
        name: 'Демисезонная куртка',
        shortDescription: 'Демисезонная куртка для весны и осени.',
        suitableFor: ['Демисезонная форма', 'Корпоративная одежда', 'Весна/осень'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место нанесения'],
        features: ['Демисезонный крой', 'Лёгкий утеплитель', 'Функциональные карманы'],
        variants: [
          {
            id: 'jacket-demi-ss',
            name: 'Демисезонная Softshell',
            subtitle: 'Softshell демисезон',
            description: 'Демисезонная куртка из Softshell для переходных сезонов.',
            features: ['Softshell', 'Демисезонная', 'Ветрозащита'],
            suitableFor: ['Весна/осень', 'Корпоративная форма', 'Outdoor'],
            colorOptions: [...BASE_COLORS, { name: 'Графит', hex: '#374151' }],
            materialOptions: ['Softshell'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'jacket-demi-wind',
            name: 'Демисезонная ветровка',
            subtitle: 'Рипстоп демисезон',
            description: 'Демисезонная ветровка из полиэстера рипстоп.',
            features: ['Полиэстер рипстоп', 'Лёгкий вес', 'Демисезонная'],
            suitableFor: ['Весна/осень', 'Корпоративная форма', 'Промо'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Полиэстер рипстоп'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 4,
        isActive: true,
      },
      {
        id: 'work-jacket',
        slug: 'work-jacket',
        name: 'Рабочая куртка',
        shortDescription: 'Прочная рабочая куртка для технических служб и производства.',
        suitableFor: ['Технический персонал', 'Производство', 'Рабочая форма'],
        brandingOptions: JACKET_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размерная сетка', 'Место нанесения'],
        features: ['Прочный материал', 'Усиленные зоны', 'Рабочий фасон'],
        variants: [
          {
            id: 'jacket-work-basic',
            name: 'Рабочая базовая',
            subtitle: 'Смесовая ткань',
            description: 'Базовая рабочая куртка из смесовой ткани.',
            features: ['Смесовая ткань', 'Прочная', 'Рабочий крой'],
            suitableFor: ['Технический персонал', 'Производство', 'Рабочая форма'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Смесовая ткань'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Размер', 'Место нанесения'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'jacket-work-heavy',
            name: 'Рабочая усиленная',
            subtitle: 'Кордура или усиленная',
            description: 'Усиленная рабочая куртка из кордуры или смесовой усиленной ткани.',
            features: ['Кордура или усиленная смеска', 'Максимальная прочность', 'Усиленные швы'],
            suitableFor: ['Тяжёлые условия работы', 'Строительство', 'Промышленность'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Кордура', 'Смесовая усиленная'],
            densityOptions: [],
            sizeOptions: JACKET_SIZES,
            brandingOptions: JACKET_BRANDING,
            placements: JACKET_PLACEMENTS,
            configurableOptions: ['Цвет', 'Материал', 'Размер', 'Место нанесения'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 5,
        isActive: true,
      },
    ],
  },

  dozhdeviki: {
    categorySlug: 'dozhdeviki',
    categoryTitle: 'Дождевики',
    models: [
      {
        id: 'raincoat-coat',
        slug: 'raincoat-coat',
        name: 'Дождевик-плащ',
        shortDescription: 'Классический дождевик-плащ для промо и мероприятий.',
        suitableFor: ['Промо-мероприятия', 'Фестивали', 'Корпоративные подарки'],
        brandingOptions: RAIN_BRANDING,
        configurableOptions: ['Цвет', 'Материал', 'Размер', 'Нанесение'],
        features: ['EVA или нейлон', 'Капюшон', 'Лёгкий вес'],
        variants: [
          {
            id: 'rain-coat-basic',
            name: 'Плащ EVA',
            subtitle: 'EVA-плащ',
            description: 'Лёгкий дождевик-плащ из EVA для промо и фестивалей.',
            features: ['EVA 70 или 100 мкм', 'Лёгкий', 'Одноразовый или многоразовый'],
            suitableFor: ['Промо-мероприятия', 'Фестивали', 'Раздаточный мерч'],
            colorOptions: [{ name: 'Прозрачный', hex: '#e2e8f0' }, ...BASE_COLORS],
            materialOptions: ['EVA 70 мкм', 'EVA 100 мкм'],
            densityOptions: [],
            sizeOptions: ['S/M', 'M/L', 'L/XL', 'XL/XXL'],
            brandingOptions: RAIN_BRANDING,
            placements: ['Спина', 'Грудь (левая)'],
            configurableOptions: ['Цвет', 'Толщина EVA', 'Размер', 'Нанесение'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'rain-coat-nylon',
            name: 'Плащ нейлоновый',
            subtitle: 'Нейлоновый плащ',
            description: 'Многоразовый нейлоновый плащ-дождевик для корпоративных нужд.',
            features: ['Нейлон Taffe', 'Многоразовый', 'Складывается компактно'],
            suitableFor: ['Корпоративные подарки', 'Outdoor-мероприятия', 'Регулярное использование'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Нейлон Taffe'],
            densityOptions: [],
            sizeOptions: ['S/M', 'M/L', 'L/XL', 'XL/XXL'],
            brandingOptions: RAIN_BRANDING,
            placements: ['Спина', 'Грудь (левая)'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: 'raincoat-poncho',
        slug: 'raincoat-poncho',
        name: 'Дождевик-пончо',
        shortDescription: 'Пончо универсального размера для масштабных мероприятий.',
        suitableFor: ['Фестивали', 'Массовые мероприятия', 'Промо'],
        brandingOptions: RAIN_BRANDING,
        configurableOptions: ['Цвет', 'Толщина пленки', 'Нанесение'],
        features: ['Универсальный размер', 'PEVA', 'Компактное хранение'],
        variants: [
          {
            id: 'rain-poncho-peva',
            name: 'Пончо PEVA basic',
            subtitle: 'PEVA базовое',
            description: 'Базовое пончо из PEVA для массовых мероприятий.',
            features: ['PEVA 60 или 80 мкм', 'Универсальный размер', 'Лёгкое'],
            suitableFor: ['Фестивали', 'Массовые мероприятия', 'Раздаточный мерч'],
            colorOptions: [{ name: 'Прозрачный', hex: '#e2e8f0' }, ...BASE_COLORS],
            materialOptions: ['PEVA 60 мкм', 'PEVA 80 мкм'],
            densityOptions: [],
            sizeOptions: ['Один размер'],
            brandingOptions: RAIN_BRANDING,
            placements: ['Спина', 'Грудь'],
            configurableOptions: ['Цвет', 'Толщина пленки', 'Нанесение'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'rain-poncho-festival',
            name: 'Пончо фестивальный',
            subtitle: 'Фестивальный',
            description: 'Пончо фестивального формата из плотного PEVA 80 мкм.',
            features: ['PEVA 80 мкм', 'Фестивальный формат', 'Яркая печать'],
            suitableFor: ['Фестивали', 'Outdoor-события', 'Промо'],
            colorOptions: [{ name: 'Прозрачный', hex: '#e2e8f0' }, ...BASE_COLORS],
            materialOptions: ['PEVA 80 мкм'],
            densityOptions: [],
            sizeOptions: ['Один размер'],
            brandingOptions: RAIN_BRANDING,
            placements: ['Спина', 'Грудь'],
            configurableOptions: ['Цвет', 'Нанесение'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 2,
        isActive: true,
      },
      {
        id: 'raincoat-eva',
        slug: 'raincoat-eva',
        name: 'Плотный EVA дождевик',
        shortDescription: 'Плотный EVA дождевик для длительного использования.',
        suitableFor: ['Регулярное использование', 'Корпоративные подарки', 'Промо'],
        brandingOptions: RAIN_BRANDING,
        configurableOptions: ['Цвет', 'Толщина EVA', 'Размер', 'Нанесение'],
        features: ['Плотный EVA', 'Долговечность', 'Капюшон'],
        variants: [
          {
            id: 'rain-eva-100',
            name: 'EVA 100 мкм',
            subtitle: 'Плотный EVA',
            description: 'Плотный дождевик из EVA 100 мкм для многоразового использования.',
            features: ['EVA 100 мкм', 'Плотный', 'Многоразовый'],
            suitableFor: ['Регулярное использование', 'Корпоративные подарки', 'Промо'],
            colorOptions: [{ name: 'Прозрачный', hex: '#e2e8f0' }, ...BASE_COLORS],
            materialOptions: ['EVA 100 мкм'],
            densityOptions: [],
            sizeOptions: ['S/M', 'M/L', 'L/XL', 'XL/XXL'],
            brandingOptions: RAIN_BRANDING,
            placements: ['Спина', 'Грудь (левая)'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'rain-eva-premium',
            name: 'EVA Premium с капюшоном',
            subtitle: 'Премиальный EVA',
            description: 'Премиальный дождевик EVA с улучшенным капюшоном.',
            features: ['EVA Premium', 'Улучшенный капюшон', 'Премиальные детали'],
            suitableFor: ['Корпоративные подарки', 'Имиджевое промо', 'Фестивали'],
            colorOptions: [{ name: 'Прозрачный', hex: '#e2e8f0' }, ...BASE_COLORS],
            materialOptions: ['EVA Premium'],
            densityOptions: [],
            sizeOptions: ['S/M', 'M/L', 'L/XL', 'XL/XXL'],
            brandingOptions: RAIN_BRANDING,
            placements: ['Спина', 'Грудь (левая)'],
            configurableOptions: ['Цвет', 'Размер', 'Нанесение'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 3,
        isActive: true,
      },
      {
        id: 'raincoat-corporate',
        slug: 'raincoat-corporate',
        name: 'Корпоративный дождевик',
        shortDescription: 'Корпоративный дождевик с расширенным брендированием.',
        suitableFor: ['Корпоративная форма', 'Представительские подарки', 'Мероприятия'],
        brandingOptions: ['Шелкография', 'Шевроны', 'DTF-печать', 'Бирки'],
        configurableOptions: ['Цвет', 'Материал', 'Размер', 'Брендирование'],
        features: ['Нейлон рипстоп', 'Корпоративный стиль', 'Расширенное брендирование'],
        variants: [
          {
            id: 'rain-corp-nylon',
            name: 'Нейлон с логотипом',
            subtitle: 'Корпоративный нейлон',
            description: 'Корпоративный дождевик из нейлона рипстоп с расширенным брендированием.',
            features: ['Нейлон рипстоп', 'Молния', 'Капюшон с козырьком'],
            suitableFor: ['Корпоративная форма', 'Представительские подарки', 'Мероприятия'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Нейлон рипстоп'],
            densityOptions: [],
            sizeOptions: ['S/M', 'M/L', 'L/XL', 'XL/XXL'],
            brandingOptions: ['Шелкография', 'Шевроны', 'DTF-печать', 'Бирки'],
            placements: ['Спина', 'Грудь (левая)', 'Рукав'],
            configurableOptions: ['Цвет', 'Размер', 'Брендирование'],
            sortOrder: 1,
            isActive: true,
          },
          {
            id: 'rain-corp-zip',
            name: 'На молнии корпоративный',
            subtitle: 'Молния + корпоратив',
            description: 'Корпоративный дождевик на молнии из нейлона или полиэстера.',
            features: ['Молния по центру', 'Нейлон Taffe или полиэстер', 'Боковые карманы'],
            suitableFor: ['Корпоративные подарки', 'Выездные мероприятия', 'Промо'],
            colorOptions: BASE_COLORS,
            materialOptions: ['Нейлон Taffe', 'Полиэстер'],
            densityOptions: [],
            sizeOptions: ['S/M', 'M/L', 'L/XL', 'XL/XXL'],
            brandingOptions: ['Шелкография', 'Шевроны', 'DTF-печать', 'Бирки'],
            placements: ['Спина', 'Грудь (левая)'],
            configurableOptions: ['Цвет', 'Материал', 'Размер', 'Нанесение'],
            sortOrder: 2,
            isActive: true,
          },
        ],
        sortOrder: 4,
        isActive: true,
      },
    ],
  },
};
