export interface PortfolioCaseProduct {
  id: string;
  title: string;
  categorySlug?: string;
  description: string;
  quantity?: string;
  material?: string;
  color?: string;
  branding?: string[];
  characteristics: string[];
  images: string[];
  sortOrder: number;
  isActive: boolean;
  tags?: string[];
}

export interface PortfolioCase {
  slug: string;
  title: string;
  shortTitle: string;
  clientType: string;
  industry: string;
  task: string;
  result: string;
  description: string;
  products: string[];
  technologies: string[];
  quantity: string;
  timeline: string;
  year: number;
  coverLabel: string;
  galleryLabels: string[];
  seoTitle: string;
  seoDescription: string;
  tags: string[];
  relatedCatalog: string[];
  relatedBranding: string[];
  /** Optional admin-extended fields (preserved when round-tripped through the admin). */
  coverImage?: string;
  galleryImages?: string[];
  caseProducts?: PortfolioCaseProduct[];
  sortOrder?: number;
  isActive?: boolean;
}

export const portfolioCases: PortfolioCase[] = [
  {
    slug: 'yunarmiya-merch-tekstil',
    title: 'Юнармия: брендированный мерч и текстиль',
    shortTitle: 'Юнармия — мерч и форма',
    clientType: 'Военно-патриотическое движение',
    industry: 'Госструктуры · образование',
    task: 'Брендированный мерч и текстильная линейка для движения «Юнармия»: единый красный фирменный стиль на одежде, бомберах и сувенирной группе для подразделений по всей стране.',
    result: 'Изготовили 4 модели верха (свитшоты оверсайз и классика, свитшот на молнии, бомбер «Пилот»). Нанесение — вышивка по плотному трикотажу, DTF-печать на молнии. Поставки партиями по подразделениям, фирменный красный акцент сохранён во всех изделиях.',
    description: 'Юнармия — всероссийское военно-патриотическое движение: дисциплина, активный отдых, историческая память. Задача — узнаваемость в каждом предмете: единый красный фирменный акцент, точное соответствие гайдлайнам и стабильное качество от партии к партии. Подобрали трикотаж 280–300 г/м², согласовали оттенок хаки и песочного по образцам, протестировали вышивку и DTF на pre-production sample.',
    products: ['Свитшоты оверсайз и классика (хаки, 600 шт.)', 'Свитшоты на молнии (песочные, 500 шт.)', 'Бомберы «Пилот» с вышивкой (300 шт.)'],
    technologies: ['Вышивка', 'DTF-печать', 'Брендированные бирки'],
    quantity: '1400+ изделий',
    timeline: 'Партиями по подразделениям',
    year: 2024,
    coverLabel: 'Юнармия — мерч и текстиль',
    galleryLabels: ['Свитшот хаки оверсайз', 'Свитшот классика — крупно', 'Свитшот на молнии — песочный', 'Бомбер «Пилот» — синий', 'Вышивка логотипа крупно'],
    seoTitle: 'Кейс: Юнармия — брендированный мерч, форма и бомберы | TEEON',
    seoDescription: 'Пошив корпоративной формы для движения «Юнармия»: свитшоты, бомберы «Пилот», вышивка и DTF-печать в едином красном стиле. 1400+ изделий партиями по подразделениям.',
    tags: ['svitshoty', 'kurtki', 'vyshivka', 'dtf-pechat', 'merch', 'forma', 'gos'],
    relatedCatalog: ['svitshoty', 'kurtki'],
    relatedBranding: ['vyshivka', 'dtf-pechat', 'birki'],
    isActive: true,
    galleryImages: [
      'http://185.225.34.60:9000/teeon-images/portfolio/1779623257775-5108.webp',
    ],
    caseProducts: [
      {
        id: '1779623266360-z58g',
        title: 'Свитшот Оверсайз',
        description: 'Оверсайз-свитшот цвета хаки из плотного хлопкового футера с вышивкой логотипа на груди.',
        quantity: '300 шт',
        material: 'Хлопок',
        color: 'хаки',
        branding: ['вышевка'],
        characteristics: ['Хлопок 280 г/м²', 'Свободный oversize-крой', 'Машинная вышивка в два цвета нити'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779623334587-5103.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779623361774-5116.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['svitshoty', 'vyshivka'],
      },
      {
        id: '1779623382192-4qsm',
        title: 'Свитшот Классика',
        description: 'Классический свитшот цвета хаки с вышитым логотипом — для повседневной формы участников движения.',
        quantity: '300 шт',
        material: 'хлопок',
        color: 'Хаки',
        branding: ['Вышевка'],
        characteristics: ['Хлопковый футер 280 г/м²', 'Прямой крой', 'Вышивка на груди слева'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779623441103-5127.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779623457188-5131.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779623471510-5134.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['svitshoty', 'vyshivka'],
      },
      {
        id: '1779623476015-iy4q',
        title: 'Свитшот на молнии ',
        description: 'Свитшот на молнии цвета песок — практичная модель для весны/осени с DTF-печатью логотипа.',
        quantity: '500 шт',
        material: 'Хлопок',
        color: 'Песочный',
        branding: ['ДТФ Печать'],
        characteristics: ['Хлопок с начёсом', 'Полная молния YKK', 'DTF-печать стойкая к стирке'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779623603875-5143.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779623627917-5160.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['svitshoty', 'dtf-pechat'],
      },
      {
        id: '1779684822250-g9vm',
        title: 'Бомбер Пилот',
        categorySlug: 'kurtki',
        description: 'Бомбер «Пилот» из плотного футера 300 г/м² в фирменном синем оттенке с вышивкой шеврона.',
        quantity: '300 шт',
        material: 'Хлопок',
        color: 'Синий',
        branding: ['Вышивка'],
        characteristics: ['Футер 300 г/м²', 'Манжеты и пояс — рибана', 'Вышивка логотипа на груди'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684886775-5206.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684918761-5205.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684944477-5201.webp',
        ],
        sortOrder: 4,
        isActive: true,
        tags: ['kurtki', 'vyshivka'],
      },
    ],
  },
  {
    slug: 'rsv-rossiya-strana-vozmojnostey',
    title: 'Россия — страна возможностей: мерч для финалов и слётов',
    shortTitle: 'РСВ — мерч-комплект',
    clientType: 'АНО «Россия — страна возможностей»',
    industry: 'Госструктуры · молодёжные проекты',
    task: 'Мерч-комплект для финалов и слётов проектов АНО «Россия — страна возможностей» (РСВ): 1000 белых и 1000 синих оверсайз-футболок плюс 1500 сумок-шопперов с фирменным нанесением.',
    result: 'Изготовили 2000 оверсайз-футболок с шелкографией пуф, DTF-печатью и светоотражающими бирками (1000 белых, 1000 синих) и 1500 сумок-шопперов со светоотражающими бирками. Единый стиль для двух цветовых волн участников.',
    description: 'АНО «Россия — страна возможностей» — государственная платформа кадровых конкурсов и социальных лифтов, создана по инициативе Президента в 2018 году. На платформе — более 25 миллионов участников из 89 регионов и 150 стран. Мерч нужен был под очные финалы и слёты: чёткое деление команд по цвету, узнаваемость в толпе и в кадре, светоотражающий акцент в дизайне.',
    products: ['Оверсайз-футболки белые (1000 шт.)', 'Оверсайз-футболки синие (1000 шт.)', 'Сумки-шопперы белые (1500 шт.)'],
    technologies: ['Шелкография', 'Шелкография пуф', 'DTF-печать', 'Светоотражающие бирки'],
    quantity: '3500 изделий',
    timeline: 'К датам очных финалов',
    year: 2024,
    coverLabel: 'РСВ — мерч-комплект финала',
    galleryLabels: ['Футболка белая — вид спереди', 'Футболка синяя — крупно', 'Шелкография пуф крупно', 'Сумка-шоппер белая', 'Светоотражающая бирка'],
    seoTitle: 'Кейс: РСВ — мерч для финалов «Россия страна возможностей» | TEEON',
    seoDescription: 'Мерч-комплект для АНО «Россия — страна возможностей»: 2000 оверсайз-футболок (белые + синие) и 1500 сумок-шопперов. Шелкография пуф, DTF, светоотражающие бирки.',
    tags: ['futbolki', 'sumki', 'shelkografiya', 'dtf-pechat', 'birki', 'merch', 'event', 'gos'],
    relatedCatalog: ['futbolki', 'sumki'],
    relatedBranding: ['shelkografiya', 'dtf-pechat', 'birki'],
    isActive: true,
    caseProducts: [
      {
        id: '1779695999703-l2kz',
        title: 'Футболка оверсайз',
        categorySlug: 'futbolki',
        description: 'Белая оверсайз-футболка с шелкографией пуф, DTF-печатью и светоотражающей биркой — основной цвет финала.',
        quantity: '1000 шт',
        color: 'Белый',
        branding: ['Шелкография Пуф', 'DTF-печать', 'Бирка светоотражающая', 'Шелкография'],
        characteristics: ['Хлопок 180–200 г/м²', 'Шелкография пуф (объёмный логотип)', 'Светоотражающая бирка'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696095110-0461.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696144141-0466.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696174545-0468.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696207328-0470.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696240504-0472.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat', 'shelkografiya'],
      },
      {
        id: '1779696249616-ccze',
        title: 'Футболка оверсайз',
        categorySlug: 'futbolki',
        description: 'Синяя оверсайз-футболка с тем же набором нанесений — параллельная цветовая партия под второй поток участников.',
        quantity: '1000 шт',
        color: 'Синий',
        branding: ['Шелкография Пуф', 'DTF-печать', 'Бирка светоотражающая', 'Шелкография'],
        characteristics: ['Хлопок 180–200 г/м²', 'Шелкография пуф + DTF', 'Светоотражающая бирка'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696300872-0505.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696326360-0509.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696358361-0511.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696385352-0513.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696407149-0515.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat', 'shelkografiya'],
      },
      {
        id: '1779696412336-wmg3',
        title: 'Сумка шопер',
        categorySlug: 'sumki',
        description: 'Белая сумка-шоппер со светоотражающей биркой — практичный мерч-носитель для участников и гостей.',
        quantity: '1500 шт',
        color: 'Белый',
        branding: ['Светоотражающая бирка'],
        characteristics: ['Хлопковый канвас', 'Удлинённые ручки', 'Светоотражающая бирка-аксессуар'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696466849-0499.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696493934-0501.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779696508530-0522.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['sumki'],
      },
    ],
  },
  {
    slug: 'sakura-sf-korporativnaya-odezhda',
    title: 'Sakura S/F: корпоративная одежда и аксессуары',
    shortTitle: 'Sakura S/F — fashion-линейка',
    clientType: 'Автозапчасти',
    industry: 'Автоиндустрия',
    task: 'Корпоративная одежда и аксессуары для бренда автозапчастей Sakura S/F с фирменными красно-белыми и красно-жёлтыми акцентами в строгой fashion-сетке.',
    result: 'Сшили линейку: бейсболки (350 шт.), поло, жилетки, худи на молнии и рюкзаки с бирками (500 шт.). Сохранили цветовую айдентику Sakura, нанесение — флекстран и вышивка, фурнитура и бирки в фирменной палитре.',
    description: 'Sakura S/F — бренд автозапчастей. Хотели модную fashion-подачу в строгой сетке: единые интервалы, аккуратные фото, фирменные красно-чёрно-белые акценты. Подобрали плотный трикотаж и хлопок-саржу под флекстран, согласовали оттенок красного по Pantone и протестировали нанесение на образцах до запуска.',
    products: ['Бейсболки чёрные (350 шт.)', 'Рюкзаки с ПВХ-бирками (500 шт.)', 'Поло, жилетки, худи на молнии'],
    technologies: ['Вышивка', 'Флекстран', 'ПВХ-бирки'],
    quantity: '1350+ изделий',
    timeline: 'Партиями под сезон',
    year: 2024,
    coverLabel: 'Sakura S/F — корпоративная одежда',
    galleryLabels: ['Бейсболка с вышивкой', 'Рюкзак с бирками', 'Поло с флекстраном', 'Жилетка с вышивкой', 'Худи на молнии'],
    seoTitle: 'Кейс: Sakura S/F — корпоративная одежда автозапчастей | TEEON',
    seoDescription: 'Линейка корпоративной одежды и аксессуаров Sakura S/F: бейсболки, рюкзаки, поло, жилетки, худи. Флекстран и вышивка в фирменных красно-белых акцентах.',
    tags: ['polo', 'hudi', 'zhiletki', 'kepki', 'sumki', 'vyshivka', 'forma', 'merch'],
    relatedCatalog: ['hudi', 'zhiletki', 'sumki'],
    relatedBranding: ['vyshivka', 'shelkografiya', 'birki'],
    isActive: true,
    galleryImages: [
      'http://185.225.34.60:9000/teeon-images/portfolio/1779682003553-4994.webp',
    ],
    caseProducts: [
      {
        id: '1779681818654-ccs9',
        title: 'Бейсболка однотонная',
        description: 'Однотонная чёрная бейсболка с вышивкой логотипа Sakura — базовый элемент корпоративного гардероба.',
        quantity: '350 шт',
        material: 'Хлопок',
        color: 'черный',
        branding: ['Вышевка'],
        characteristics: ['Хлопок 100%', 'Регулируемый ремешок сзади', 'Машинная вышивка'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779681864054-4977.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['vyshivka'],
      },
      {
        id: '1779683768843-1u0h',
        title: 'Рюкзак с бирками',
        categorySlug: 'sumki',
        description: 'Чёрный рюкзак с фирменными ПВХ-бирками и нанесением флекстраном — практичный аксессуар для команды и партнёров.',
        quantity: '500 шт',
        color: 'черный',
        branding: ['Флекстран', 'ПВХ Бирки'],
        characteristics: ['Курточная ткань', 'Отделение для ноутбука', 'ПВХ-бирки с логотипом'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779683906417-4984.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779683922437-4985.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779683942197-4992.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['sumki'],
      },
      {
        id: '1779698792609-wn8v',
        title: 'Футболка Поло',
        categorySlug: 'futbolki',
        description: 'Поло Sakura с флекстран-нанесением — для офиса и фирменных стендов.',
        material: 'Хлопок-пике',
        color: 'Чёрный',
        branding: ['Флекстран'],
        characteristics: ['Пике 220 г/м²', 'Стойкий воротник', 'Флекстран-логотип'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698816866-0530.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698838370-0532.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['futbolki'],
      },
      {
        id: '1779698853412-krl3',
        title: 'Жилетка',
        categorySlug: 'zhiletki',
        description: 'Жилетка в фирменных цветах с машинной вышивкой логотипа.',
        material: 'Оксфорд + утеплитель',
        color: 'Чёрный',
        branding: ['Вышивка'],
        characteristics: ['Лёгкий синтепон', 'Высокая горловина', 'Вышивка на груди'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698895221-0563.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698913935-0576.webp',
        ],
        sortOrder: 4,
        isActive: true,
        tags: ['vyshivka', 'zhiletki'],
      },
      {
        id: '1779698930216-2ixt',
        title: 'Худи на молнии',
        categorySlug: 'hudi',
        description: 'Худи на молнии с нанесением флекстраном — основа межсезонного комплекта.',
        material: 'Хлопок с начёсом',
        color: 'Чёрный',
        branding: ['Флекстран'],
        characteristics: ['Полная молния', 'Капюшон с подкладом', 'Флекстран по груди'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698954167-0583.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699025990-0588.webp',
        ],
        sortOrder: 5,
        isActive: true,
        tags: ['hudi'],
      },
    ],
  },
  {
    slug: 'nibk-korporativnaya-odezhda',
    title: 'NIBK: корпоративная одежда с фиолетовыми акцентами',
    shortTitle: 'NIBK — фирменная форма',
    clientType: 'Автокомпоненты',
    industry: 'Автоиндустрия',
    task: 'Корпоративная одежда и аксессуары в фирменной чёрно-фиолетовой палитре бренда NIBK: зип-худи, жилетки на синтепоне, поло, рюкзаки и бейсболки.',
    result: 'Изготовили зип-худи классик (500 шт.), жилетки на синтепоне 100 (700 шт.), поло 220 г/м² (500 шт.), рюкзаки с флекстраном и ПВХ-бирками (500 шт.) и бейсболки. Единый стиль с фиолетовыми акцентами выдержан на одежде и аксессуарах.',
    description: 'NIBK — бренд автокомпонентов (тормозные системы, диски, колодки). Линейка сделана в одной визуальной сетке с Sakura S/F, но с собственной палитрой: фиолетовый как ключевой акцент. Согласовали оттенок по Pantone, тестировали воспроизведение на трикотаже, оксфорде и фурнитуре.',
    products: ['Зип-худи классик (500 шт.)', 'Жилетки на синтепоне (700 шт.)', 'Поло 220 г/м² (500 шт.)', 'Рюкзаки с флекстраном (500 шт.)', 'Бейсболки с вышивкой'],
    technologies: ['Вышивка', 'Флекстран', 'ПВХ-бирки'],
    quantity: '2200+ изделий',
    timeline: 'Партиями под сезон',
    year: 2024,
    coverLabel: 'NIBK — корпоративная одежда',
    galleryLabels: ['Зип-худи классик', 'Жилетка на синтепоне', 'Бейсболка с вышивкой', 'Рюкзак NIBK', 'Поло 220 г/м²'],
    seoTitle: 'Кейс: NIBK — корпоративная одежда автокомпонентов | TEEON',
    seoDescription: 'Фирменная форма NIBK в чёрно-фиолетовой палитре: 500 худи, 700 жилеток, 500 поло, рюкзаки и бейсболки. Вышивка, флекстран, ПВХ-бирки. Партиями под сезон.',
    tags: ['polo', 'hudi', 'zhiletki', 'kepki', 'sumki', 'vyshivka', 'forma', 'merch'],
    relatedCatalog: ['hudi', 'zhiletki', 'sumki'],
    relatedBranding: ['vyshivka', 'shelkografiya', 'birki'],
    isActive: true,
    caseProducts: [
      {
        id: '1779684068924-eo50',
        title: 'Худи на молнии',
        description: 'Классическое зип-худи в чёрном цвете с фиолетовым подкладом капюшона и нанесением флекстраном.',
        quantity: '500 шт',
        material: 'Хлопок',
        color: 'Черный',
        branding: ['Флекстран'],
        characteristics: ['Хлопок с начёсом', 'Полная молния YKK', 'Фиолетовый акцент подклада'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684115133-5016.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684128011-5019.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684147425-5012.webp',
        ],
        sortOrder: 1,
        isActive: true,
      },
      {
        id: '1779684239840-052u',
        title: 'Жилетка',
        categorySlug: 'zhiletki',
        description: 'Жилетка на синтепоне 100 г/м² в чёрном цвете с вышивкой логотипа NIBK.',
        quantity: '700 шт',
        material: 'Полистер+ Синтипон',
        color: 'Черный',
        branding: ['Вышивка'],
        characteristics: ['Полистер + синтепон 100', 'Машинная вышивка', 'Карманы на молнии'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684297299-5077.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684308287-5068.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684348487-5083.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['zhiletki', 'vyshivka'],
      },
      {
        id: '1779684401724-e8tr',
        title: 'Бейсболка',
        description: 'Чёрная бейсболка с вышивкой логотипа NIBK — финальный аксессуар комплекта.',
        branding: ['Вышивка'],
        characteristics: ['Хлопок-саржа', 'Регулируемая застёжка', 'Машинная вышивка'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684421522-5053.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['vyshivka'],
      },
      {
        id: '1779684438682-j0kw',
        title: 'Рюкзак',
        categorySlug: 'sumki',
        description: 'Корпоративный рюкзак с флекстраном и ПВХ-бирками в фирменной палитре.',
        quantity: '500 шт',
        branding: ['Флекстран', 'ПВХ Бирки'],
        characteristics: ['Курточная ткань', 'Лямки с уплотнителем', 'Бирки и флекстран-логотип'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684483297-5059.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684500530-5061.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684516919-5062.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684533065-5065.webp',
        ],
        sortOrder: 4,
        isActive: true,
        tags: ['sumki'],
      },
      {
        id: '1779684542256-es00',
        title: 'Футбока Поло',
        categorySlug: 'futbolki',
        description: 'Поло 220 г/м² в чёрном цвете с нанесением флекстраном — для офиса и презентаций.',
        quantity: '500 шт',
        material: 'Хлопок',
        color: 'черынй',
        branding: ['Флекстран'],
        characteristics: ['Пике 220 г/м²', 'Усиленный воротник', 'Флекстран-логотип'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684562935-5088.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779684646527-5091.webp',
        ],
        sortOrder: 5,
        isActive: true,
        tags: ['futbolki'],
      },
    ],
  },
  {
    slug: 'agrorus-i-ko-podarochnyy-nabor',
    title: 'Агрорус и Ко: подарочный набор для агросектора',
    shortTitle: 'Агрорус и Ко — мерч в зелёной палитре',
    clientType: 'Агрохимия и защита растений',
    industry: 'АПК',
    task: 'Корпоративная одежда для агросектора: чистая зелёная палитра, природные акценты и практичные изделия для офиса, поля и партнёров.',
    result: 'Собрали комплект: белые лонгсливы с вышивкой, куртки-ветровки с вышитым логотипом, базовые футболки цвета хаки с DTF-печатью. Подача спокойная, акцент на надёжность и сезонность поставок.',
    description: 'Агрорус и Ко — комплексные решения для сельского хозяйства: агрохимия, защита растений, удобрения, агрономия. Подача — в духе агросектора: зелёные тона, природные акценты, акцент на надёжность. Изделия рассчитаны на офис и выезды на поля: вышивка по плотному хлопку, DTF-печать на базовых футболках.',
    products: ['Лонгсливы белые с вышивкой', 'Куртки-ветровки с вышитым логотипом', 'Базовые футболки хаки с DTF-печатью'],
    technologies: ['Вышивка', 'DTF-печать', 'Брендированные бирки'],
    quantity: 'Линейка под потребность',
    timeline: 'Партиями под сезон',
    year: 2024,
    coverLabel: 'Агрорус и Ко — мерч для агросектора',
    galleryLabels: ['Лонгслив белый', 'Куртка-ветровка', 'Футболка базовая хаки', 'Вышивка крупно', 'Деталь брендирования'],
    seoTitle: 'Кейс: Агрорус и Ко — корпоративная одежда для агросектора | TEEON',
    seoDescription: 'Мерч для компании «Агрорус и Ко» в зелёной фирменной палитре: лонгсливы, ветровки, футболки хаки. Вышивка и DTF-печать. Для офиса, выездов и партнёров.',
    tags: ['longslivy', 'futbolki', 'kurtki', 'vyshivka', 'dtf-pechat', 'merch', 'agro'],
    relatedCatalog: ['longslivy', 'futbolki', 'kurtki'],
    relatedBranding: ['vyshivka', 'dtf-pechat', 'birki'],
    isActive: true,
    caseProducts: [
      {
        id: '1779694030487-zx5c',
        title: 'Лонгслив',
        categorySlug: 'longslivy',
        description: 'Белый лонгслив с вышивкой логотипа на груди — лёгкая базовая модель для офиса и выездов.',
        material: 'Хлопок',
        color: 'Белый',
        branding: ['Вышивка'],
        characteristics: ['Хлопок 100%', 'Машинная вышивка', 'Подходит под слоистый комплект'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694070104-0029.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694087893-0032.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['longslivy', 'vyshivka'],
      },
      {
        id: '1779694135345-fj0x',
        title: 'Кутка ветровка',
        categorySlug: 'kurtki',
        description: 'Куртка-ветровка в фирменных цветах с вышитым логотипом — практичная защита от ветра для полевых выездов.',
        branding: ['Вышивка'],
        characteristics: ['Курточная ткань', 'Подкладка из сетки', 'Вышивка логотипа на груди'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694153550-0043.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694170213-0051.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694186242-0053.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['kurtki', 'vyshivka'],
      },
      {
        id: '1779694240221-e7fx',
        title: 'Футболка базова',
        description: 'Базовая футболка цвета хаки с DTF-печатью логотипа — повседневный элемент мерч-комплекта.',
        material: 'Хлопок',
        color: 'Хаки',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок 180 г/м²', 'Прямой крой', 'Стойкая DTF-печать'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694271443-0071.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694292832-0073.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat'],
      },
      {
        id: '1779699096437-cze3',
        title: 'Футболка базова',
        description: 'Базовая футболка цвета хаки — дополнительная партия с тем же нанесением для расширения комплекта.',
        material: 'Хлопок',
        color: 'Хаки',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок 180 г/м²', 'Прямой крой', 'DTF-печать в один цвет'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699127519-22379.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699151401-22386.webp',
        ],
        sortOrder: 4,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat'],
      },
    ],
  },
  {
    slug: 'vic-veterinary-merch',
    title: 'ВИК (VIC): полевая форма и фирменный мерч',
    shortTitle: 'ВИК — форма ветсервиса',
    clientType: 'Ветеринарная фармацевтика',
    industry: 'Здоровье животных · агросектор',
    task: 'Полевая форма и брендированный мерч для группы компаний ВИК — российского лидера в производстве ветеринарных препаратов и кормовых добавок. Нужны были практичные изделия для выездного персонала и единый стиль для офиса.',
    result: 'Изготовили красные ветровки для полевых выездов (500 шт.), синие худи на молнии (300 шт.), двухсторонние дождевики, оверсайз-футболки с DTF-печатью и фартуки с велкро-шевронами для технологов. Все нанесения — в фирменной красно-белой палитре ВИК.',
    description: 'Группа компаний ВИК — крупнейший производитель ветеринарных препаратов и кормовых добавок в СНГ, единственная ветфарм-компания с европейским сертификатом GMP. Сотрудники работают на животноводческих комплексах в полевых условиях, нужна была практичная и узнаваемая форма: ветровка для полевых выездов, худи для межсезонья, двухсторонний дождевик и фартук-шеврон для технологов на производстве.',
    products: ['Ветровки красные (500 шт.)', 'Худи на молнии синие (300 шт.)', 'Двухсторонние дождевики', 'Оверсайз-футболки с DTF', 'Фартуки с велкро-шевронами'],
    technologies: ['DTF-печать', 'Вышивка', 'Шевроны на липучке', 'Тиснение'],
    quantity: '800+ изделий',
    timeline: 'Партиями под сезон',
    year: 2024,
    coverLabel: 'ВИК — полевая форма и мерч',
    galleryLabels: ['Ветровка красная — вид спереди', 'Худи синее на молнии', 'Двухсторонний дождевик', 'Оверсайз-футболка', 'Фартук с велкро'],
    seoTitle: 'Кейс: ВИК (VIC) — полевая форма для ветфармацевтики | TEEON',
    seoDescription: 'Пошив корпоративной формы для группы компаний ВИК: 500 красных ветровок, 300 синих худи, дождевики, футболки и фартуки с DTF-печатью и шевронами для полевого ветсервиса.',
    tags: ['kurtki', 'hudi', 'futbolki', 'dozhdeviki', 'dtf-pechat', 'vyshivka', 'shevrony', 'forma', 'agro'],
    relatedCatalog: ['kurtki', 'hudi', 'futbolki', 'dozhdeviki'],
    relatedBranding: ['dtf-pechat', 'vyshivka', 'shevrony'],
    isActive: true,
    caseProducts: [
      {
        id: '1779692088060-30k5',
        title: 'Ветровка',
        categorySlug: 'kurtki',
        description: 'Красная ветровка из плотной курточной ткани с DTF-печатью логотипа ВИК на спине — для полевых выездов специалистов.',
        quantity: '500 шт',
        material: 'Курточная ткань',
        color: 'Красный',
        branding: ['DTF-печать'],
        characteristics: ['Курточная ткань с мембраной', 'Регулируемый низ', 'Крупная DTF-печать на спине'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692126160-5231.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692171442-5234.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692189575-5238.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692207920-5239.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['kurtki', 'dtf-pechat'],
      },
      {
        id: '1779692251284-rph3',
        title: 'Худи на молнии',
        categorySlug: 'hudi',
        description: 'Синее худи на молнии из плотного хлопка с вышитым логотипом — для межсезонья и базы.',
        quantity: '300 шт',
        material: 'Хлопок',
        color: 'Синий',
        branding: ['Вышивка'],
        characteristics: ['Хлопок с начёсом', 'Полная молния YKK', 'Машинная вышивка логотипа'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692273485-5254.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692291522-5265.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692378395-5268.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['hudi', 'vyshivka'],
      },
      {
        id: '1779692402263-jfzt',
        title: 'Двухсторонний дождевик',
        categorySlug: 'dozhdeviki',
        description: 'Двухсторонний дождевик с DTF-печатью с обеих сторон — практичная защита от дождя для полевой команды.',
        branding: ['DTF-печать'],
        characteristics: ['PEVA с двусторонней печатью', 'Капюшон-затяжка', 'Компактно складывается'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692435369-5291.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692456438-5292.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692487277-5294.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692498208-5297.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692522105-5310.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692545962-5314.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['dozhdeviki', 'dtf-pechat'],
      },
      {
        id: '1779692565808-dkhh',
        title: 'Футболка Оверсаз',
        categorySlug: 'futbolki',
        description: 'Оверсайз-футболка с DTF-печатью логотипа — для корпоративных мероприятий и команды.',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок 180 г/м²', 'Свободный oversize-крой', 'DTF-печать на спине/груди'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692592299-5325.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692624361-5330.webp',
        ],
        sortOrder: 4,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat'],
      },
      {
        id: '1779692670870-pv7z',
        title: 'Фартук с велкро',
        description: 'Фартук с велкро-зоной для шевронов и тиснёным логотипом — для технологов на производстве.',
        branding: ['Шевроны', 'Тиснение'],
        characteristics: ['Плотный хлопок-саржа', 'Велкро-зона на груди', 'Сменные шевроны в комплекте'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692703911-5341.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692733478-5344.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779692762765-5352.webp',
        ],
        sortOrder: 5,
        isActive: true,
        tags: ['shevrony', 'tisnenie'],
      },
    ],
  },
  {
    slug: 'alean-tour-operator-merch',
    title: 'Алеан: корпоративный мерч для туроператора',
    shortTitle: 'Алеан — мерч и форма',
    clientType: 'Туроператор',
    industry: 'Туризм · внутренний туризм',
    task: 'Корпоративный мерч и форма для национального туроператора Алеан — для гидов, представителей в принимающих офисах (Сочи, Геленджик, Анапа, Крым, Кисловодск, Минск) и подарочных наборов партнёрам-турагентствам.',
    result: 'Собрали комплект: чёрные оверсайз-футболки и свитшоты с DTF-печатью, пуховые жилетки (750 шт.) с ПВХ-шевронами и бирками, сумки-шопперы с велкро-зоной для сменных шевронов под направления.',
    description: 'Алеан — национальный туроператор с 1993 года, работает по более чем 60 регионам России и СНГ, сотрудничает с 15 000 турагентств. Принимающие офисы на курортах: Сочи, Геленджик, Анапа, Симферополь, Кисловодск, Минск, Баку. Нужен был мерч-комплект, в котором гид и представитель узнаваемы, а команда выглядит едино независимо от региона. Велкро-шевроны на жилетках и сумках позволяют менять обозначение направления.',
    products: ['Оверсайз-футболки чёрные (хлопок)', 'Свитшоты с DTF-печатью', 'Пуховые жилетки (750 шт.)', 'Сумки-шопперы с велкро-зоной'],
    technologies: ['DTF-печать', 'ПВХ-шевроны', 'Велкро-шевроны', 'Брендированные бирки'],
    quantity: '1000+ изделий',
    timeline: 'Партиями под сезон',
    year: 2024,
    coverLabel: 'Алеан — мерч для туроператора',
    galleryLabels: ['Футболка чёрная оверсайз', 'Свитшот с DTF', 'Пуховая жилетка', 'Сумка-шоппер с велкро', 'Деталь шеврона'],
    seoTitle: 'Кейс: Алеан — корпоративный мерч для туроператора | TEEON',
    seoDescription: 'Мерч для национального туроператора Алеан: футболки, свитшоты, 750 пуховых жилеток, сумки-шопперы. DTF-печать, ПВХ-шевроны, велкро под смену направлений. Партиями под сезон.',
    tags: ['futbolki', 'svitshoty', 'zhiletki', 'sumki', 'dtf-pechat', 'shevrony', 'birki', 'merch', 'forma'],
    relatedCatalog: ['futbolki', 'svitshoty', 'zhiletki', 'sumki'],
    relatedBranding: ['dtf-pechat', 'birki', 'shevrony'],
    isActive: true,
    caseProducts: [
      {
        id: '1779694397258-coy5',
        title: 'Футболка Оверсайз',
        categorySlug: 'futbolki',
        description: 'Чёрная оверсайз-футболка из хлопка с DTF-печатью логотипа Алеан — базовый элемент формы гидов.',
        material: 'Хлопок',
        color: 'Черный',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок 180 г/м²', 'Свободный oversize-крой', 'Стойкая DTF-печать'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694422661-0100.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694458434-0108.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat'],
      },
      {
        id: '1779694466433-hf7u',
        title: 'Свитшот',
        categorySlug: 'svitshoty',
        description: 'Свитшот с DTF-печатью логотипа — для прохладного сезона и вечерних мероприятий.',
        material: 'Хлопок',
        branding: ['DTF-печать'],
        characteristics: ['Хлопковый футер', 'DTF-печать на груди', 'Прямой крой'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694486409-0116.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694506355-0119.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['svitshoty', 'dtf-pechat'],
      },
      {
        id: '1779699185670-ewqk',
        title: 'Жилетка пухонабивка',
        categorySlug: 'zhiletki',
        description: 'Пуховая жилетка тиражом 750 штук — для холодного сезона на курортах. ПВХ-шевроны и брендированные бирки.',
        quantity: '750 шт',
        branding: ['ПВХ Шиврон', 'Бирки'],
        characteristics: ['Пухонабивка', 'ПВХ-шеврон с логотипом', 'Брендированные бирки с инструкцией'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699241358-22457.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699265182-22462.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699279287-22465.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699306011-22469.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['zhiletki', 'birki'],
      },
      {
        id: '1779699326591-kydq',
        title: 'Футболка Оверсайз',
        categorySlug: 'futbolki',
        description: 'Вторая партия оверсайз-футболок — для расширения комплекта представителей в принимающих офисах.',
        material: 'Хлопок',
        color: 'Черный',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок 180 г/м²', 'Тот же DTF-логотип', 'Дополнительный тираж'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699360546-22492.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699382013-22496.webp',
        ],
        sortOrder: 4,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat'],
      },
      {
        id: '1779699388640-wr6v',
        title: 'Сумка Шопер с велкро',
        categorySlug: 'sumki',
        description: 'Сумка-шоппер с велкро-зоной для сменных шевронов — позволяет менять обозначение курорта/направления.',
        branding: ['Бирки', 'Велкро+Шивроны на липучке'],
        characteristics: ['Хлопковый канвас', 'Велкро-зона на лицевой стороне', 'Бирки с инструкцией ухода'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699434510-22474.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699454909-22478.webp',
        ],
        sortOrder: 5,
        isActive: true,
        tags: ['sumki', 'birki'],
      },
    ],
  },
  {
    slug: 'liftprom-corporate-vests',
    title: 'ЛИФТПРОМ: жилетки и рюкзаки для монтажников',
    shortTitle: 'ЛИФТПРОМ — комплект монтажника',
    clientType: 'Производство лифтов и подъёмников',
    industry: 'Промышленное оборудование',
    task: 'Брендированный комплект для монтажной бригады компании ЛИФТПРОМ — производителя грузовых лифтов и подъёмников: жилетки и рюкзаки с фирменным нанесением.',
    result: 'Сшили практичные жилетки с DTF-печатью логотипа и комплект рюкзаков с DTF-нанесением и брендированными бирками. Изделия рассчитаны на работу на объектах: от складов и производственных цехов до коттеджного монтажа.',
    description: 'ЛИФТПРОМ — производитель грузовых лифтов и подъёмников из Самары: коттеджные лифты, гаражные подъёмники, оборудование для производств, складов и ресторанов. Грузоподъёмность изделий — до 5 000 кг, высота подъёма до 40 метров. Монтажные бригады работают на объектах по всей России, нужна была форма, в которой команда узнаваема и которая выдерживает выезды.',
    products: ['Жилетки с DTF-печатью', 'Рюкзаки монтажные с бирками'],
    technologies: ['DTF-печать', 'Брендированные бирки'],
    quantity: 'Партия под штат монтажников',
    timeline: '10–14 рабочих дней',
    year: 2024,
    coverLabel: 'ЛИФТПРОМ — комплект монтажника',
    galleryLabels: ['Жилетка с DTF', 'Рюкзак — вид спереди', 'Деталь нанесения', 'Бирка с логотипом', 'Комплект'],
    seoTitle: 'Кейс: ЛИФТПРОМ — жилетки и рюкзаки для монтажной бригады | TEEON',
    seoDescription: 'Брендированный комплект для монтажников компании ЛИФТПРОМ (Самара, производство лифтов): жилетки и рюкзаки с DTF-печатью и фирменными бирками. Срок 10–14 дней.',
    tags: ['zhiletki', 'sumki', 'dtf-pechat', 'birki', 'forma', 'merch'],
    relatedCatalog: ['zhiletki', 'sumki'],
    relatedBranding: ['dtf-pechat', 'birki'],
    isActive: true,
    caseProducts: [
      {
        id: '1779694613761-kmiz',
        title: 'Жилетка',
        categorySlug: 'zhiletki',
        description: 'Рабочая жилетка с DTF-печатью логотипа ЛИФТПРОМ — практичный верх для монтажников на объектах.',
        branding: ['DTF-печать'],
        characteristics: ['Прочная курточная ткань', 'Накладные карманы', 'DTF-печать стойкая к стирке'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694693978-0153.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694716820-0161.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['zhiletki', 'dtf-pechat'],
      },
      {
        id: '1779694721090-t5fd',
        title: 'Рюкзак',
        categorySlug: 'sumki',
        description: 'Рюкзак с DTF-печатью и брендированными бирками — для инструмента и личных вещей монтажной бригады.',
        branding: ['DTF-печать', 'Бирки'],
        characteristics: ['Курточная ткань', 'Усиленные лямки', 'DTF + бирка с логотипом'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694748363-0148.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694785147-0150.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694798619-0166.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['sumki', 'dtf-pechat', 'birki'],
      },
    ],
  },
  {
    slug: 'mistral-tretyakov-collab',
    title: 'Мистраль × Третьяковская галерея: коллаб-капсула',
    shortTitle: 'Мистраль × Третьяковка — капсула',
    clientType: 'FMCG · искусство',
    industry: 'Продукты питания · культура',
    task: 'Капсульная коллекция мерча для коллаборации бренда «Мистраль» (производитель риса, круп и бобовых с 1992 года) и Третьяковской галереи: 8 моделей одежды и аксессуаров с авторскими принтами.',
    result: 'Изготовили линейку из 8 позиций: жилетка Мистраль, две оверсайз-футболки, худи-кенгуру, два свитшота-поло, сумка-шоппер, ещё две оверсайз-футболки в цветах мокко и базовом хлопке. Все нанесения — DTF-печать, под сложные сюжетные принты с репродукциями.',
    description: 'Коллаборация двух сильных брендов: «Мистраль» — российский производитель риса, круп и бобовых премиального сегмента (с 1992 года, представлен во всех федеральных сетях), и Третьяковская галерея — главный музей русского искусства. Капсула рассчитана на любителей еды и искусства одновременно: спокойные базовые цвета, фактурный хлопок, DTF-печать под высокую детализацию репродукций.',
    products: ['Жилетка Мистраль', 'Худи-кенгуру чёрное', 'Свитшоты-поло (2 модели)', 'Оверсайз-футболки (хлопок, мокко)', 'Сумка-шоппер'],
    technologies: ['DTF-печать'],
    quantity: 'Капсульная коллекция',
    timeline: 'К запуску коллаборации',
    year: 2024,
    coverLabel: 'Мистраль × Третьяковка — капсула',
    galleryLabels: ['Жилетка Мистраль', 'Футболка с принтом', 'Худи-кенгуру', 'Свитшот-поло', 'Сумка-шоппер', 'Цвет мокко'],
    seoTitle: 'Кейс: Мистраль × Третьяковская галерея — капсула мерча | TEEON',
    seoDescription: 'Капсульная коллаборация бренда «Мистраль» и Третьяковской галереи: 8 моделей одежды и сумок с авторскими DTF-принтами. Жилетки, худи-кенгуру, футболки оверсайз, шопперы.',
    tags: ['zhiletki', 'futbolki', 'hudi', 'svitshoty', 'sumki', 'dtf-pechat', 'merch', 'kollaboraciya'],
    relatedCatalog: ['hudi', 'futbolki', 'svitshoty', 'sumki'],
    relatedBranding: ['dtf-pechat'],
    isActive: true,
    caseProducts: [
      {
        id: '1779694868090-ksp6',
        title: 'Жилетка Мистраль',
        categorySlug: 'zhiletki',
        description: 'Жилетка коллаборации с DTF-принтом — премиальная база капсулы.',
        branding: ['DTF-печать'],
        characteristics: ['Плотная ткань', 'DTF-печать под сложный принт', 'Капсульная маркировка'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694911951-0185.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694927882-0196.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['zhiletki', 'dtf-pechat'],
      },
      {
        id: '1779694931861-fagq',
        title: 'Футболка Оверсайз',
        categorySlug: 'futbolki',
        description: 'Оверсайз-футболка с DTF-печатью репродукции — основа коллекции.',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок 180–220 г/м²', 'Свободный oversize-крой', 'Высокодетализированная DTF-печать'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779694956470-0197.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695033683-0204.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['dtf-pechat', 'futbolki'],
      },
      {
        id: '1779695062254-v5yj',
        title: 'Худи кингуру',
        categorySlug: 'hudi',
        description: 'Худи-кенгуру в чёрном цвете с принтом коллаборации.',
        color: 'Черный',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок с начёсом', 'Кенгуру-карман', 'DTF под крупный принт'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695106564-0218.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695133118-0225.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695147985-0221.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['hudi', 'dtf-pechat'],
      },
      {
        id: '1779695155296-5yrz',
        title: 'Свитшот Поло',
        categorySlug: 'svitshoty',
        description: 'Свитшот-поло с DTF-нанесением — необычная для капсулы конструкция с воротником на пуговицах.',
        branding: ['DTF-печать'],
        characteristics: ['Хлопковый футер', 'Воротник-поло', 'DTF-печать на груди'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695229555-0259.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695278184-0265.webp',
        ],
        sortOrder: 4,
        isActive: true,
        tags: ['svitshoty', 'dtf-pechat'],
      },
      {
        id: '1779695283784-3e6h',
        title: 'Сумка Шопер',
        categorySlug: 'sumki',
        description: 'Сумка-шоппер с DTF-печатью — носимый артефакт коллаборации.',
        branding: ['DTF-печать'],
        characteristics: ['Хлопковый канвас', 'Удлинённые ручки', 'DTF под фотопринт'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695313318-0270.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695342867-0275.webp',
        ],
        sortOrder: 5,
        isActive: true,
        tags: ['sumki', 'dtf-pechat'],
      },
      {
        id: '1779695348409-968q',
        title: 'Свитшот поло',
        categorySlug: 'svitshoty',
        description: 'Второй вариант свитшота-поло — другой принт коллаборации.',
        branding: ['DTF-печать'],
        characteristics: ['Хлопковый футер', 'Воротник-поло', 'DTF-печать'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695371388-0284.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695387974-0286.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695408538-0290.webp',
        ],
        sortOrder: 6,
        isActive: true,
        tags: ['svitshoty', 'dtf-pechat'],
      },
      {
        id: '1779695420254-al67',
        title: 'Футболка Оверсайз',
        categorySlug: 'futbolki',
        description: 'Оверсайз-футболка из плотного хлопка с DTF-печатью — версия в базовом светлом цвете.',
        material: 'Хлопок',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок плотный', 'Oversize-крой', 'DTF-печать с высокой детализацией'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695445085-0316.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695489990-0323.webp',
        ],
        sortOrder: 7,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat'],
      },
      {
        id: '1779695515038-sghp',
        title: 'Футболка оверсайз',
        categorySlug: 'futbolki',
        description: 'Оверсайз-футболка цвета мокко — мягкий тёплый оттенок капсулы.',
        color: 'Мокко',
        branding: ['DTF-печать'],
        characteristics: ['Хлопок плотный', 'Цвет мокко', 'DTF-печать репродукции'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695554205-0333.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695580729-0338.webp',
        ],
        sortOrder: 8,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat'],
      },
    ],
  },
  {
    slug: 'rodnye-korma-vests',
    title: 'Родные корма: жилетки для команды и кинологов',
    shortTitle: 'Родные корма — фирменные жилетки',
    clientType: 'Корма для домашних животных',
    industry: 'Pet food · ритейл',
    task: 'Брендированные жилетки для торговых представителей и амбассадоров бренда «Родные корма» — российского производителя кормов для собак и кошек премиум-сегмента.',
    result: 'Сшили два варианта жилеток с DTF-печатью логотипа: один — для торговых представителей в зоомагазинах, второй — для выездных мероприятий и выставок с кинологами и заводчиками.',
    description: 'Бренд «Родные корма» появился в 2015 году у компании «Пет Кер Компани»: российский продукт на 100% — сырьё, упаковка, рецептура. Корма позиционируются как премиум-класс, работа идёт через зоомагазины, выставки и партнёрских кинологов. Жилетки нужны для двух сценариев: торговые точки и выезды на собачьи мероприятия.',
    products: ['Жилетки для торговых представителей', 'Жилетки для выездов и выставок'],
    technologies: ['DTF-печать'],
    quantity: 'Партия для команды',
    timeline: '10–14 рабочих дней',
    year: 2024,
    coverLabel: 'Родные корма — жилетки команды',
    galleryLabels: ['Жилетка вариант 1', 'Деталь нанесения', 'Жилетка вариант 2', 'Логотип крупно', 'Бирка'],
    seoTitle: 'Кейс: Родные корма — фирменные жилетки команды | TEEON',
    seoDescription: 'Брендированные жилетки для российского производителя кормов «Родные корма»: два варианта для торговых представителей и выездных мероприятий. DTF-печать логотипа.',
    tags: ['zhiletki', 'dtf-pechat', 'forma', 'merch', 'pet'],
    relatedCatalog: ['zhiletki'],
    relatedBranding: ['dtf-pechat'],
    isActive: true,
    caseProducts: [
      {
        id: '1779695671790-nnb4',
        title: 'Жилетка',
        categorySlug: 'zhiletki',
        description: 'Жилетка для торговых представителей с DTF-печатью логотипа «Родные корма» — для работы в зоомагазинах и выкладок.',
        branding: ['DTF-печать'],
        characteristics: ['Лёгкая курточная ткань', 'DTF-печать на спине', 'Удобна поверх свитера'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695712047-0360.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695736970-0374.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695780264-0384.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['zhiletki', 'dtf-pechat'],
      },
      {
        id: '1779695785440-sada',
        title: 'Жилетка',
        categorySlug: 'zhiletki',
        description: 'Жилетка для выездных мероприятий и выставок — с DTF-печатью, более насыщенный фирменный акцент.',
        branding: ['DTF-печать'],
        characteristics: ['Утеплённая модель', 'Крупное DTF-нанесение', 'Карманы для каталогов'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695833429-0409.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695858594-0414.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695894393-0416.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779695933616-0417.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['zhiletki', 'dtf-pechat'],
      },
    ],
  },
  {
    slug: 'sibur-merch-tekstil',
    title: 'СИБУР: фирменный мерч и текстильная линейка',
    shortTitle: 'СИБУР — корпоративный набор',
    clientType: 'Нефтехимия и полимеры',
    industry: 'Промышленность',
    task: 'Чистый технологичный мерч в бирюзово-белой палитре СИБУР: единый корпоративный набор для сотрудников, партнёров и event-команд.',
    result: 'Собрали фирменный набор: рюкзак с ПВХ-шевроном и DTF, футболка-оверсайз, два варианта худи и бейсболка со вставкой с гранулами. Аккуратное нанесение в бирюзово-белой палитре, единая визуальная логика на всём комплекте.',
    description: 'СИБУР — нефтехимия, полимеры, газопереработка, энергетика, инновации. Нужен был чистый технологичный стиль с единой логикой во всём наборе: один логотип, один цвет, одно ощущение от каждого предмета. Подобрали плотные ткани, согласовали оттенок бирюзы по Pantone, протестировали нанесение на образце до запуска тиража. Использовали DTF-печать, ПВХ-шевроны и фирменные бирки.',
    products: ['Рюкзак с ПВХ-шевроном', 'Футболка оверсайз с DTF-печатью', 'Худи с шевронами (два цветовых варианта)', 'Бейсболка со вставкой с гранулами'],
    technologies: ['DTF-печать', 'ПВХ-шевроны', 'Брендированные бирки'],
    quantity: 'Корпоративный набор',
    timeline: 'Партиями под потребность',
    year: 2024,
    coverLabel: 'СИБУР — фирменный набор мерча',
    galleryLabels: ['Рюкзак СИБУР', 'Футболка оверсайз', 'Худи — крупный план', 'Худи второй цвет', 'Бейсболка'],
    seoTitle: 'Кейс: СИБУР — фирменный мерч и корпоративный набор | TEEON',
    seoDescription: 'Корпоративный набор мерча для СИБУР в бирюзово-белой палитре: рюкзак, футболка, два худи, бейсболка. DTF-печать, ПВХ-шевроны, брендированные бирки.',
    tags: ['hudi', 'futbolki', 'sumki', 'dtf-pechat', 'birki', 'merch'],
    relatedCatalog: ['hudi', 'futbolki', 'sumki'],
    relatedBranding: ['dtf-pechat', 'birki', 'shevrony'],
    isActive: true,
    caseProducts: [
      {
        id: '1779697256819-6fbk',
        title: 'Рюкзак',
        categorySlug: 'sumki',
        description: 'Корпоративный рюкзак с ПВХ-шевроном, DTF-печатью и фирменной вставкой с гранулами в палитре СИБУР.',
        color: 'Бирюзово-чёрный',
        branding: ['ПВХ Шиврон', 'DTF-печать', 'Вставка с гранулами'],
        characteristics: ['Прочная курточная ткань', 'Объёмный карман с молнией', 'ПВХ-шеврон + DTF-печать'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697312199-0602.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697388108-0609.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['sumki', 'dtf-pechat'],
      },
      {
        id: '1779697520933-wsgr',
        title: 'Футболка оверсайз',
        categorySlug: 'futbolki',
        description: 'Футболка оверсайз с DTF-печатью логотипа и фирменной биркой — для корпоративных мероприятий и команды.',
        material: 'Хлопок 180 г/м²',
        color: 'Белый',
        branding: ['DTF-печать', 'ПВХ шиврон', 'Бирки'],
        characteristics: ['Свободный oversize-крой', 'Двойная отстрочка ворота', 'DTF-печать + ПВХ-шеврон'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697596260-0613.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697625227-0617.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697656488-0621.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['futbolki', 'dtf-pechat', 'birki'],
      },
      {
        id: '1779697663327-0nny',
        title: 'Худи',
        categorySlug: 'hudi',
        description: 'Худи в фирменных цветах СИБУР с DTF-печатью, шевроном и бирками — основа корпоративного образа.',
        material: 'Хлопок с начёсом 300 г/м²',
        color: 'Бирюзовый',
        branding: ['DTF-печать', 'Бирки', 'ПВХ Шиврон'],
        characteristics: ['Кенгуру-карман', 'Шнурки в тон', 'Полный комплект брендирования'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697708898-0646.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697762453-0652.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697798957-0656.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697824914-0662.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['dtf-pechat', 'birki', 'hudi'],
      },
      {
        id: '1779697840810-sm0f',
        title: 'Бейсболка',
        description: 'Бейсболка с тиснёным логотипом и вставкой из фирменных полимерных гранул — отсылка к производственной специфике СИБУР.',
        color: 'Белый',
        branding: ['Вставка с гранулами', 'Шиврон'],
        characteristics: ['Хлопковая саржа', 'Регулируемый бэк', 'Уникальная вставка с гранулами'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779697916740-0671.webp',
        ],
        sortOrder: 4,
        isActive: true,
      },
      {
        id: '1779698710142-taoo',
        title: 'Худи',
        categorySlug: 'hudi',
        description: 'Второй цветовой вариант худи — для разных команд и сезонов, с тем же набором брендирования.',
        material: 'Хлопок с начёсом 300 г/м²',
        color: 'Белый',
        branding: ['DTF-печать', 'Бирки', 'ПВХ Шиврон'],
        characteristics: ['Кенгуру-карман', 'DTF-печать + ПВХ-шеврон', 'Сатиновая бирка с составом'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698743854-0734.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698770955-0744.webp',
        ],
        sortOrder: 5,
        isActive: true,
        tags: ['dtf-pechat', 'birki', 'hudi'],
      },
    ],
  },
  {
    slug: 'indrive-merch-capsule',
    title: 'inDrive: брендированный мерч с неоновыми акцентами',
    shortTitle: 'inDrive — мерч-капсула',
    clientType: 'Международный сервис заказа поездок',
    industry: 'Mobility · IT',
    task: 'Капсула фирменного мерча для международной компании inDrive — для команды, амбассадоров и партнёрских мероприятий. Узнаваемые неоновые акценты бренда, премиальное качество фурнитуры.',
    result: 'Сшили чёрно-белые оверсайз-футболки с ПВХ-шевронами и бирками, два худи в фирменных цветах (неон и графит) с DTF-печатью, брендированными шнурками и люверсами с гравировкой логотипа.',
    description: 'inDrive — международный сервис заказа поездок, основан в Якутске в 2012 году, работает в 1065 городах в 48 странах, приложение загружено более 400 миллионов раз. Бренд узнаваем по неоновым акцентам — нужно было перенести их в текстиль и аксессуары без потери чистоты цвета. Использовали стойкую DTF-печать, брендированные шнурки и гравированные люверсы.',
    products: ['Оверсайз-футболки чёрно-белые', 'Худи неоновое с DTF', 'Худи графитовое с DTF'],
    technologies: ['DTF-печать', 'ПВХ-шевроны', 'Брендированные бирки', 'Брендированные шнурки', 'Люверсы с гравировкой'],
    quantity: 'Капсула под команду и амбассадоров',
    timeline: 'Партиями',
    year: 2024,
    coverLabel: 'inDrive — мерч-капсула',
    galleryLabels: ['Футболка чёрно-белая', 'Худи неоновое', 'Худи графитовое', 'Деталь люверса', 'Брендированный шнурок'],
    seoTitle: 'Кейс: inDrive — мерч-капсула с неоновыми акцентами | TEEON',
    seoDescription: 'Брендированная мерч-капсула для международного сервиса inDrive: оверсайз-футболки, неоновое и графитовое худи. DTF-печать, ПВХ-шевроны, гравированные люверсы.',
    tags: ['futbolki', 'hudi', 'dtf-pechat', 'birki', 'shevrony', 'merch', 'kapsula'],
    relatedCatalog: ['futbolki', 'hudi'],
    relatedBranding: ['dtf-pechat', 'birki', 'shevrony'],
    isActive: true,
    caseProducts: [
      {
        id: '1779697973457-15bp',
        title: 'Футболка оверсайз',
        categorySlug: 'futbolki',
        description: 'Оверсайз-футболка в чёрно-белом колорите с ПВХ-шевроном и фирменными бирками.',
        color: 'Черный-белый',
        branding: ['Бирки', 'ПВХ Шиврон'],
        characteristics: ['Хлопок 200 г/м²', 'Контрастные швы', 'ПВХ-шеврон с логотипом'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698032647-0681.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698062223-0687.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698133474-0689.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['futbolki', 'birki'],
      },
      {
        id: '1779698194229-r7yu',
        title: 'Худи',
        categorySlug: 'hudi',
        description: 'Худи в фирменном неоновом цвете с DTF-печатью, брендированными шнурками и гравированными люверсами.',
        color: 'Неон',
        branding: ['DTF-печать', 'Бирки', 'Брендированные шнурки', 'Люверсы с гравровкой'],
        characteristics: ['Хлопок с начёсом 300 г/м²', 'Неоновый акцент бренда', 'Гравированные люверсы'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698235683-0711.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698260480-0717.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698284921-0721.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['dtf-pechat', 'birki', 'hudi'],
      },
      {
        id: '1779698338379-uuee',
        title: 'Худи',
        categorySlug: 'hudi',
        description: 'Худи в графитовом цвете — спокойная альтернатива неону, тот же набор брендирования.',
        color: 'Графит',
        branding: ['DTF-печать', 'Бирки', 'Брендированные шнурки', 'Люверсы с гравровкой'],
        characteristics: ['Хлопок с начёсом 300 г/м²', 'Графитовый базовый цвет', 'DTF + гравированные люверсы'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698391129-0761.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698412177-0765.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779698442805-0767.webp',
        ],
        sortOrder: 3,
        isActive: true,
        tags: ['dtf-pechat', 'birki', 'hudi'],
      },
    ],
  },
  {
    slug: 'itelma-corporate-jackets',
    title: 'Итэлма: куртки-анораки и шопперы для R&D-команды',
    shortTitle: 'Итэлма — куртки и аксессуары',
    clientType: 'Автомобильная электроника',
    industry: 'Промышленность · R&D',
    task: 'Корпоративная одежда для группы компаний «Итэлма» — российского разработчика и производителя автомобильной электроники: куртка-анорак для инженеров и фирменный шоппер с практичной фурнитурой.',
    result: 'Сшили куртки-анораки с DTF-печатью и брендированными бирками для R&D и производственных площадок в Москве, Костроме и Димитровграде, плюс шопперы со светоотражающей биркой и велкро-зоной для сменных шевронов отделов.',
    description: 'Группа компаний «Итэлма» — более 30 лет на рынке автомобильной электроники: кузовные системы, управление двигателем, комбинации приборов, ЭРА-ГЛОНАСС, телематика, ADAS. 3000 сотрудников, 1000 из них — в R&D. Производственные площадки в Москве, Костроме и Димитровграде. Нужна была одежда, которая объединяет инженерные и производственные команды и при этом выглядит технологично.',
    products: ['Куртки-анораки с DTF-печатью', 'Шопперы со светоотражающими бирками'],
    technologies: ['DTF-печать', 'Брендированные бирки', 'Велкро-шевроны', 'Светоотражающие бирки'],
    quantity: 'Партия под штат',
    timeline: '14–18 рабочих дней',
    year: 2024,
    coverLabel: 'Итэлма — корпоративная одежда',
    galleryLabels: ['Куртка-анорак — вид спереди', 'DTF-печать крупно', 'Сумка-шоппер', 'Светоотражающая бирка', 'Велкро-зона'],
    seoTitle: 'Кейс: Итэлма — куртки-анораки для R&D-команды | TEEON',
    seoDescription: 'Корпоративная одежда для группы компаний «Итэлма» (автомобильная электроника): куртки-анораки с DTF-печатью, шопперы со светоотражающими бирками и велкро-зоной шевронов.',
    tags: ['kurtki', 'sumki', 'dtf-pechat', 'birki', 'shevrony', 'forma', 'merch'],
    relatedCatalog: ['kurtki', 'sumki'],
    relatedBranding: ['dtf-pechat', 'birki', 'shevrony'],
    isActive: true,
    caseProducts: [
      {
        id: '1779699490382-h6gh',
        title: 'Куртка Анарак',
        categorySlug: 'kurtki',
        description: 'Куртка-анорак с DTF-печатью логотипа и брендированными бирками — для инженеров R&D-центров и производственных площадок.',
        branding: ['DTF-печать', 'Бирки'],
        characteristics: ['Курточная ткань с мембраной', 'Конструкция анорак с центральным карманом', 'Брендированные бирки'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699541593-22506.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699555670-22515.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699570854-22512.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699582775-22516.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699592916-0001.webp',
        ],
        sortOrder: 1,
        isActive: true,
        tags: ['kurtki', 'dtf-pechat', 'birki'],
      },
      {
        id: '1779699598948-ngql',
        title: 'Сумка шопер',
        categorySlug: 'sumki',
        description: 'Сумка-шоппер со светоотражающей биркой и велкро-зоной для сменных шевронов отделов.',
        branding: ['Светоотражающая бирка', 'Велкро'],
        characteristics: ['Хлопковый канвас', 'Светоотражающая бирка', 'Велкро под шевроны отделов'],
        images: [
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699632934-0009.webp',
          'http://185.225.34.60:9000/teeon-images/portfolio/1779699642943-0006.webp',
        ],
        sortOrder: 2,
        isActive: true,
        tags: ['sumki'],
      },
    ],
  },
];

export const portfolioCaseMap: Record<string, PortfolioCase> = Object.fromEntries(
  portfolioCases.map((c) => [c.slug, c])
);

export function getPortfolioCase(slug: string): PortfolioCase | undefined {
  return portfolioCaseMap[slug];
}

export function getRelatedPortfolioCases(currentSlug: string, limit = 3): PortfolioCase[] {
  const current = portfolioCaseMap[currentSlug];
  if (!current) return portfolioCases.slice(0, limit);

  return portfolioCases
    .filter((c) => c.slug !== currentSlug)
    .map((c) => ({
      case: c,
      score: c.tags.filter((t) => current.tags.includes(t)).length,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.case);
}

export function getPortfolioCasesByTag(tag: string): PortfolioCase[] {
  return portfolioCases.filter((c) => c.tags.includes(tag));
}

export function getAllPortfolioTags(): string[] {
  return Array.from(new Set(portfolioCases.flatMap((c) => c.tags))).sort();
}
