export interface ProductColor {
  name: string;
  hex: string;
  note?: string;
}

export interface ProductOption {
  id: string;
  title: string;
  shortDescription: string;
  imageLabel: string;
  imageSrc?: string;
  fullDescription?: string;
  materialOptions: string[];
  densityOptions: string[];
  colorOptions: ProductColor[];
  sizeOptions: string[];
  brandingOptions: string[];
  printPositions: string[];
  quantityOptions: string[];
  priceFactors: string[];
  characteristics: string[];
  useCases: string[];
  notes?: string[];
}

export interface ProductModelGroup {
  categorySlug: string;
  modelId: string;
  modelTitle: string;
  modelDescription: string;
  options: ProductOption[];
}

export type ProductOptionsMap = Record<string, ProductModelGroup[]>;

// ─── Shared constants ────────────────────────────────────────────────────────

const BASE_COLORS: ProductColor[] = [
  { name: 'Чёрный', hex: '#1a1a1a' },
  { name: 'Белый', hex: '#ffffff' },
  { name: 'Серый', hex: '#9ca3af' },
  { name: 'Тёмно-синий', hex: '#1e3a5f' },
  { name: 'Красный', hex: '#dc2626' },
  { name: 'Жёлтый', hex: '#f5c518' },
];

const STANDARD_QTY = [
  'до 50 изделий',
  '50–100 изделий',
  '100–300 изделий',
  '300–500 изделий',
  '500+ изделий',
];

const STANDARD_PRICE_FACTORS = [
  'Ткань и плотность',
  'Тираж изделий',
  'Способ нанесения',
  'Срочность',
  'Упаковка и комплектация',
];

const STANDARD_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL', 'Набор размеров'];
const HOODIE_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', 'Набор размеров'];
const VEST_JACKET_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'];

const BASIC_BRANDING = ['Шелкография', 'DTF-печать', 'DTG-печать', 'Бирки'];
const BASIC_PRINT_POSITIONS = [
  'Грудь (левая)',
  'Грудь (по центру)',
  'Спина (верх)',
  'Спина (центр)',
  'Рукав',
];

// ─── productOptions ──────────────────────────────────────────────────────────

export const productOptions: ProductOptionsMap = {

  // ═══════════════════════════════════════════════════════════════════════════
  // ФУТБОЛКИ
  // ═══════════════════════════════════════════════════════════════════════════
  futbolki: [
    {
      categorySlug: 'futbolki',
      modelId: 'basic',
      modelTitle: 'Базовая футболка',
      modelDescription:
        'Классическая промо-футболка из хлопка для мероприятий, командной одежды и welcome-наборов.',
      options: [
        {
          id: 'basic-160',
          title: 'Базовая футболка 160 г/м²',
          shortDescription: 'Лёгкая промо-футболка для массовых тиражей.',
          imageLabel: 'Базовая футболка 160 г/м²',
          materialOptions: ['Хлопок 100%', 'Хлопок/полиэстер 50/50'],
          densityOptions: ['160 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: BASIC_BRANDING,
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Хлопок 100%, плотность 160 г/м²',
            'Прямой крой',
            'Круглая горловина',
          ],
          useCases: ['Промоакции', 'Мероприятия', 'Раздача на выставках'],
        },
        {
          id: 'basic-180',
          title: 'Базовая футболка 180 г/м²',
          shortDescription: 'Стандартная футболка с хорошим соотношением качества и цены.',
          imageLabel: 'Базовая футболка 180 г/м²',
          materialOptions: ['Хлопок 100%', 'Хлопок/полиэстер 50/50'],
          densityOptions: ['180 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: BASIC_BRANDING,
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Хлопок 100%, плотность 180 г/м²',
            'Прямой крой',
            'Круглая горловина с рибаной',
          ],
          useCases: ['Корпоративная форма', 'Welcome-наборы', 'Командная одежда'],
        },
        {
          id: 'basic-reinforced',
          title: 'Базовая футболка с усиленной горловиной',
          shortDescription: 'Усиленная горловина из рибаны — лучше держит форму при носке.',
          imageLabel: 'Футболка с усиленной горловиной',
          materialOptions: ['Хлопок 100%', 'Хлопок/лайкра'],
          densityOptions: ['180 г/м²', '200 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: BASIC_BRANDING,
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Усиленная горловина из рибаны',
            'Хлопок 100% или хлопок/лайкра',
            'Плотность 180–200 г/м²',
            'Прямой крой',
          ],
          useCases: ['Долгосрочная корпоративная форма', 'Мерч-магазины', 'Подарочные наборы'],
        },
      ],
    },
    {
      categorySlug: 'futbolki',
      modelId: 'oversize',
      modelTitle: 'Футболка оверсайз',
      modelDescription:
        'Свободный крой с опущенной линией плеча для корпоративного мерча и бренд-магазинов.',
      options: [
        {
          id: 'oversize-200',
          title: 'Oversize 200 г/м²',
          shortDescription: 'Лёгкий оверсайз для летних коллекций и промо.',
          imageLabel: 'Оверсайз футболка 200 г/м²',
          materialOptions: ['Хлопок 100%', 'Хлопок меланж'],
          densityOptions: ['200 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'DTG-печать', 'Шелкография', 'Вышивка', 'Бирки'],
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Свободный крой oversize',
            'Опущенная линия плеча',
            'Хлопок 100% или меланж, 200 г/м²',
          ],
          useCases: ['Корпоративный мерч', 'Бренд-магазины', 'Lifestyle-коллекции'],
        },
        {
          id: 'oversize-220',
          title: 'Oversize 220 г/м²',
          shortDescription: 'Стандартный оверсайз — универсальный вариант для мерча.',
          imageLabel: 'Оверсайз футболка 220 г/м²',
          materialOptions: ['Хлопок 100%', 'Хлопок меланж'],
          densityOptions: ['220 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'DTG-печать', 'Шелкография', 'Вышивка', 'Бирки'],
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотность 220 г/м² — хорошее качество ткани',
            'Свободный крой',
            'Широкий выбор цветов',
          ],
          useCases: ['Мерч-магазины', 'Корпоративные подарки', 'Welcome-наборы'],
        },
        {
          id: 'oversize-240',
          title: 'Premium oversize 240 г/м²',
          shortDescription: 'Плотный оверсайз с премиальным ощущением ткани.',
          imageLabel: 'Премиум оверсайз 240 г/м²',
          materialOptions: ['Хлопок 100%', 'Хлопок меланж'],
          densityOptions: ['240 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'DTG-печать', 'Шелкография', 'Бирки'],
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Премиальная плотность 240 г/м²',
            'Плотная мягкая ткань',
            'Вышивка и 3D-нанесение',
          ],
          useCases: ['Премиум-мерч', 'Партнёрские подарки', 'Лимитированные коллекции'],
        },
        {
          id: 'oversize-washed',
          title: 'Oversize washed',
          shortDescription: 'Эффект состаренной ткани — актуальный для lifestyle-мерча.',
          imageLabel: 'Оверсайз washed',
          materialOptions: ['Хлопок 100% (washed)'],
          densityOptions: ['220 г/м²', '240 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'DTG-печать', 'Шелкография', 'Бирки'],
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Технология wash-эффекта',
            'Хлопок 100%, 220–240 г/м²',
            'Мягкий и воздушный материал',
          ],
          useCases: ['Lifestyle-мерч', 'Бренд-магазины', 'Коллаборации'],
        },
        {
          id: 'oversize-dropped',
          title: 'Oversize dropped shoulder',
          shortDescription: 'Опущенная пройма для выраженного оверсайз-кроя.',
          imageLabel: 'Оверсайз dropped shoulder',
          materialOptions: ['Хлопок 100%', 'Хлопок меланж'],
          densityOptions: ['200 г/м²', '220 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'DTG-печать', 'Шелкография', 'Вышивка', 'Бирки'],
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Выраженная опущенная пройма',
            'Свободный укороченный крой',
            'Хлопок 100% или меланж',
          ],
          useCases: ['Streetwear-мерч', 'Бренд-магазины', 'Молодёжные коллекции'],
        },
      ],
    },
    {
      categorySlug: 'futbolki',
      modelId: 'polo',
      modelTitle: 'Футболка-поло',
      modelDescription:
        'Поло-рубашка из пике для деловой формы и корпоративных мероприятий.',
      options: [
        {
          id: 'polo-200',
          title: 'Поло пике 200 г/м²',
          shortDescription: 'Классическое корпоративное поло из пике.',
          imageLabel: 'Поло пике 200 г/м²',
          materialOptions: ['Пике хлопок 100%', 'Пике хлопок/полиэстер'],
          densityOptions: ['200 г/м²'],
          colorOptions: BASE_COLORS,
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Пике хлопок 100%, 200 г/м²',
            'Пуговицы и воротник-стойка',
            'Деловой внешний вид',
          ],
          useCases: ['Корпоративная форма', 'Деловые мероприятия', 'Обслуживающий персонал'],
        },
        {
          id: 'polo-220',
          title: 'Поло пике 220 г/м²',
          shortDescription: 'Плотное поло — хороший баланс цены и качества.',
          imageLabel: 'Поло пике 220 г/м²',
          materialOptions: ['Пике хлопок 100%', 'Пике хлопок/полиэстер'],
          densityOptions: ['220 г/м²'],
          colorOptions: BASE_COLORS,
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотное пике 220 г/м²',
            'Воротник и манжеты из рибаны',
            'Долгосрочная носка',
          ],
          useCases: ['Корпоративная форма', 'Ресторанный персонал', 'Продажи и сервис'],
        },
        {
          id: 'polo-240',
          title: 'Поло премиум 240 г/м²',
          shortDescription: 'Мерсеризованный хлопок — мягче, прочнее, долговечнее.',
          imageLabel: 'Поло премиум 240 г/м²',
          materialOptions: ['Пике мерсеризованный хлопок'],
          densityOptions: ['240 г/м²'],
          colorOptions: BASE_COLORS,
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Мерсеризованный хлопок 240 г/м²',
            'Шёлковистая поверхность ткани',
            'Высокая стойкость к выцветанию',
          ],
          useCases: ['Представительская форма', 'VIP-клиенты', 'Партнёрские подарки'],
        },
      ],
    },
    {
      categorySlug: 'futbolki',
      modelId: 'sport',
      modelTitle: 'Спортивная футболка',
      modelDescription:
        'Влагоотводящие ткани для спортивных команд и outdoor-мероприятий.',
      options: [
        {
          id: 'sport-light',
          title: 'Спортивная футболка lightweight',
          shortDescription: 'Лёгкая спортивная футболка для активных мероприятий.',
          imageLabel: 'Спортивная футболка lightweight',
          materialOptions: ['Полиэстер 100%', 'Полиэстер/спандекс'],
          densityOptions: ['140 г/м²', '160 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'Шелкография', 'Сублимация'],
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Полиэстер с влагоотводом, 140–160 г/м²',
            'Лёгкая и воздухопроницаемая',
            'Быстро сохнет',
          ],
          useCases: ['Спортивные команды', 'Беговые события', 'Outdoor-активности'],
        },
        {
          id: 'sport-moisture',
          title: 'Спортивная футболка с влагоотводом',
          shortDescription: 'Специальная влагоотводящая ткань для интенсивных нагрузок.',
          imageLabel: 'Спортивная футболка с влагоотводом',
          materialOptions: ['Полиэстер 100%', 'Полиэстер/спандекс'],
          densityOptions: ['160 г/м²', '180 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'Шелкография', 'Сублимация'],
          printPositions: BASIC_PRINT_POSITIONS,
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Технология CoolDry / Dry-Fit',
            'Плоские швы без натирания',
            'Полиэстер 160–180 г/м²',
          ],
          useCases: ['Марафоны', 'Турниры', 'Корпоративный спорт'],
        },
        {
          id: 'sport-team',
          title: 'Футболка для команды',
          shortDescription: 'Командная футболка с местом под номер и имя.',
          imageLabel: 'Командная спортивная футболка',
          materialOptions: ['Полиэстер 100%', 'Полиэстер/спандекс'],
          densityOptions: ['160 г/м²', '180 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'Шелкография', 'Сублимация'],
          printPositions: ['Грудь', 'Спина (номер)', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Индивидуальные номера и имена',
            'Полиэстер с влагоотводом',
            'Плотность 160–180 г/м²',
          ],
          useCases: ['Спортивные команды', 'Корпоративные турниры', 'Школьные команды'],
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════════════════
  // ХУДИ
  // ═══════════════════════════════════════════════════════════════════════════
  hudi: [
    {
      categorySlug: 'hudi',
      modelId: 'classic-hoodie',
      modelTitle: 'Худи classic',
      modelDescription:
        'Классическое худи с капюшоном и карманом-кенгуру. Начёс или петля, плотность от 280 г/м².',
      options: [
        {
          id: 'hoodie-280',
          title: 'Худи classic 280 г/м²',
          shortDescription: 'Лёгкое классическое худи для демисезонного мерча.',
          imageLabel: 'Классическое худи 280 г/м²',
          materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['280 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Начёс хлопок, 280 г/м²',
            'Капюшон с кулиской',
            'Карман-кенгуру',
          ],
          useCases: ['Корпоративный мерч', 'Welcome-наборы', 'Командная одежда'],
        },
        {
          id: 'hoodie-320',
          title: 'Худи classic 320 г/м²',
          shortDescription: 'Плотное классическое худи для круглогодичного мерча.',
          imageLabel: 'Классическое худи 320 г/м²',
          materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['320 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотный начёс 320 г/м²',
            'Тёплый и долговечный',
            'Карман-кенгуру, манжеты рибана',
          ],
          useCases: ['Корпоративные подарки', 'Мерч-магазины', 'Осенне-зимние коллекции'],
        },
      ],
    },
    {
      categorySlug: 'hudi',
      modelId: 'oversize-hoodie',
      modelTitle: 'Худи оверсайз',
      modelDescription:
        'Оверсайз-крой с опущенной линией плеча для lifestyle-мерча и бренд-магазинов.',
      options: [
        {
          id: 'hoodie-os-320',
          title: 'Худи oversize 320 г/м²',
          shortDescription: 'Свободный крой для современного корпоративного мерча.',
          imageLabel: 'Оверсайз худи 320 г/м²',
          materialOptions: ['Петля хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['320 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Свободный оверсайз-крой',
            'Петля хлопок или начёс, 320 г/м²',
            'Опущенная линия плеча',
          ],
          useCases: ['Lifestyle-мерч', 'Молодёжные бренды', 'Бренд-магазины'],
        },
        {
          id: 'hoodie-os-360',
          title: 'Худи oversize 360 г/м²',
          shortDescription: 'Максимально плотный оверсайз для премиального мерча.',
          imageLabel: 'Оверсайз худи 360 г/м²',
          materialOptions: ['Петля хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['360 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Максимальная плотность 360 г/м²',
            'Тяжёлый оверсайз для премиума',
            'Широкие рукава и удлинённый крой',
          ],
          useCases: ['Премиум-мерч', 'Подарки партнёрам', 'Лимитированные серии'],
        },
        {
          id: 'hoodie-os-premium',
          title: 'Худи premium oversize',
          shortDescription: 'Премиальный оверсайз с расширенным выбором нанесения.',
          imageLabel: 'Худи premium oversize',
          materialOptions: ['Петля хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['340 г/м²', '360 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', '3D-вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            '3D-вышивка и объёмные нашивки',
            'Плотность 340–360 г/м²',
            'Индивидуальные нашивки и ярлыки',
          ],
          useCases: ['VIP-мерч', 'Коллаборации с брендами', 'Эксклюзивные серии'],
        },
      ],
    },
    {
      categorySlug: 'hudi',
      modelId: 'zip-hoodie',
      modelTitle: 'Худи на молнии',
      modelDescription:
        'Удобная модель на молнии — для корпоративной формы и повседневной носки.',
      options: [
        {
          id: 'hoodie-zip-basic',
          title: 'Худи zip basic',
          shortDescription: 'Базовое худи на молнии для корпоративной формы.',
          imageLabel: 'Худи на молнии basic',
          materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['280 г/м²', '300 г/м²'],
          colorOptions: BASE_COLORS,
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Молния по всей длине',
            'Начёс хлопок, 280–300 г/м²',
            'Карманы по бокам',
          ],
          useCases: ['Корпоративная форма', 'Командная одежда', 'Персонал торговли'],
        },
        {
          id: 'hoodie-zip-premium',
          title: 'Худи zip premium',
          shortDescription: 'Плотное худи на молнии с расширенными опциями нанесения.',
          imageLabel: 'Худи на молнии premium',
          materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['300 г/м²', '320 г/м²'],
          colorOptions: BASE_COLORS,
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотный начёс 300–320 г/м²',
            'Качественная молния YKK',
            'Удлинённый силуэт',
          ],
          useCases: ['Представительская форма', 'Деловые мероприятия', 'Выездные команды'],
        },
      ],
    },
    {
      categorySlug: 'hudi',
      modelId: 'special-hoodie',
      modelTitle: 'Специальные худи',
      modelDescription:
        'Двойной капюшон, карман-кенгуру и футер — нестандартные решения для lifestyle-мерча.',
      options: [
        {
          id: 'hoodie-double-hood',
          title: 'Худи с двойным капюшоном',
          shortDescription: 'Двойной капюшон для выраженного силуэта и объёма.',
          imageLabel: 'Худи с двойным капюшоном',
          materialOptions: ['Начёс хлопок', 'Петля хлопок'],
          densityOptions: ['300 г/м²', '320 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', '3D-вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Двойной капюшон — объёмный силуэт',
            'Начёс или петля хлопок, 300–320 г/м²',
            'Карман-кенгуру',
          ],
          useCases: ['Streetwear-коллекции', 'Lifestyle-мерч', 'Молодёжные бренды'],
        },
        {
          id: 'hoodie-kangaroo',
          title: 'Худи с карманом-кенгуру',
          shortDescription: 'Увеличенный карман-кенгуру — практично и узнаваемо.',
          imageLabel: 'Худи с карманом-кенгуру',
          materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['280 г/м²', '300 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Увеличенный карман-кенгуру',
            'Начёс хлопок, 280–300 г/м²',
            'Нанесение на кармане',
          ],
          useCases: ['Корпоративный мерч', 'Welcome-наборы', 'Студенческие коллекции'],
        },
        {
          id: 'hoodie-futur-premium',
          title: 'Худи на футере premium',
          shortDescription: 'Футер хлопок — мягкий и прочный материал для долгосрочного мерча.',
          imageLabel: 'Худи на футере premium',
          materialOptions: ['Футер хлопок'],
          densityOptions: ['320 г/м²', '360 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', '3D-вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Капюшон', 'Рукав', 'Карман'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Футер хлопок — гладкая внешняя поверхность',
            'Плотность 320–360 г/м²',
            'Не образует катышек',
          ],
          useCases: ['Премиум-мерч', 'Бренд-магазины', 'Корпоративные подарки'],
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════════════════
  // СВИТШОТЫ
  // ═══════════════════════════════════════════════════════════════════════════
  svitshoty: [
    {
      categorySlug: 'svitshoty',
      modelId: 'classic-sweat',
      modelTitle: 'Классический свитшот',
      modelDescription:
        'Свитшот без капюшона — чистый, лаконичный вариант для корпоративной одежды и welcome-наборов.',
      options: [
        {
          id: 'sweat-260',
          title: 'Классический свитшот 260 г/м²',
          shortDescription: 'Лёгкий свитшот для демисезонного корпоративного мерча.',
          imageLabel: 'Свитшот классический 260 г/м²',
          materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['260 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Начёс хлопок, 260 г/м²',
            'Без капюшона — деловой вид',
            'Манжеты и пояс из рибаны',
          ],
          useCases: ['Корпоративная форма', 'Welcome-наборы', 'Промо-одежда'],
        },
        {
          id: 'sweat-300',
          title: 'Классический свитшот 300 г/м²',
          shortDescription: 'Стандартный плотный свитшот для повседневного использования.',
          imageLabel: 'Свитшот классический 300 г/м²',
          materialOptions: ['Начёс хлопок', 'Начёс хлопок/полиэстер'],
          densityOptions: ['300 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотный начёс 300 г/м²',
            'Тёплый и долговечный',
            'Универсальный вид',
          ],
          useCases: ['Мерч-магазины', 'Корпоративные подарки', 'Командная одежда'],
        },
      ],
    },
    {
      categorySlug: 'svitshoty',
      modelId: 'oversize-sweat',
      modelTitle: 'Свитшот оверсайз',
      modelDescription:
        'Оверсайз-крой свитшота для lifestyle-мерча и бренд-магазинов.',
      options: [
        {
          id: 'sweat-os-basic',
          title: 'Свитшот oversize basic',
          shortDescription: 'Свободный крой для lifestyle-мерча и бренд-магазинов.',
          imageLabel: 'Свитшот оверсайз basic',
          materialOptions: ['Петля хлопок', 'Начёс хлопок'],
          densityOptions: ['280 г/м²', '300 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Свободный оверсайз-крой',
            'Петля или начёс хлопок, 280–300 г/м²',
            'Широкие рукава',
          ],
          useCases: ['Lifestyle-мерч', 'Молодёжные коллекции', 'Бренд-магазины'],
        },
        {
          id: 'sweat-os-premium',
          title: 'Свитшот oversize premium',
          shortDescription: 'Плотный премиальный оверсайз с расширенным брендингом.',
          imageLabel: 'Свитшот оверсайз premium',
          materialOptions: ['Петля хлопок', 'Начёс хлопок'],
          densityOptions: ['300 г/м²', '320 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', '3D-вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотность 300–320 г/м²',
            'Гладкая петля — без ворса',
            '3D-вышивка и объёмные нашивки',
          ],
          useCases: ['Премиум-мерч', 'Партнёрские подарки', 'Эксклюзивные коллекции'],
        },
      ],
    },
    {
      categorySlug: 'svitshoty',
      modelId: 'special-sweat',
      modelTitle: 'Специальные модели',
      modelDescription:
        'Реглан и премиальный футер — для командной одежды и подарков партнёрам.',
      options: [
        {
          id: 'sweat-raglan',
          title: 'Свитшот реглан',
          shortDescription: 'Реглановый рукав — динамичный силуэт для командной одежды.',
          imageLabel: 'Свитшот реглан',
          materialOptions: ['Смеска хлопок/полиэстер'],
          densityOptions: ['260 г/м²', '280 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'Шелкография', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Реглановый рукав',
            'Смеска хлопок/полиэстер, 260–280 г/м²',
            'Контрастные рукава (по ТЗ)',
          ],
          useCases: ['Командная одежда', 'Спортивные коллективы', 'Школьные проекты'],
        },
        {
          id: 'sweat-premium-340',
          title: 'Премиальный свитшот 340 г/м²',
          shortDescription: 'Максимальная плотность — для подарков партнёрам и мерч-магазинов.',
          imageLabel: 'Премиальный свитшот 340 г/м²',
          materialOptions: ['Футер хлопок'],
          densityOptions: ['340 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: HOODIE_SIZES,
          brandingOptions: ['Вышивка', '3D-вышивка', 'DTF-печать', 'Шевроны', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Футер хлопок 340 г/м²',
            'Гладкая внешняя поверхность',
            'Премиальное ощущение материала',
          ],
          useCases: ['VIP-подарки', 'Партнёрские наборы', 'Мерч-магазины'],
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════════════════
  // ЛОНГСЛИВЫ
  // ═══════════════════════════════════════════════════════════════════════════
  longslivy: [
    {
      categorySlug: 'longslivy',
      modelId: 'basic-ls',
      modelTitle: 'Базовый лонгслив',
      modelDescription:
        'Классический лонгслив из хлопка с манжетом из рибаны. Для промо и командной одежды.',
      options: [
        {
          id: 'ls-160',
          title: 'Базовый лонгслив 160 г/м²',
          shortDescription: 'Лёгкий лонгслив для промоакций в прохладную погоду.',
          imageLabel: 'Базовый лонгслив 160 г/м²',
          materialOptions: ['Хлопок 100%'],
          densityOptions: ['160 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина (верх)', 'Спина (центр)', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Хлопок 100%, 160 г/м²',
            'Длинный рукав с манжетом',
            'Прямой крой',
          ],
          useCases: ['Промоакции', 'Осенние мероприятия', 'Командная одежда'],
        },
        {
          id: 'ls-180',
          title: 'Базовый лонгслив 180 г/м²',
          shortDescription: 'Стандартный лонгслив — универсальный вариант для мерча.',
          imageLabel: 'Базовый лонгслив 180 г/м²',
          materialOptions: ['Хлопок 100%'],
          densityOptions: ['180 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина (верх)', 'Спина (центр)', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Хлопок 100%, 180 г/м²',
            'Плотнее — лучше держит форму',
            'Манжет из рибаны',
          ],
          useCases: ['Welcome-наборы', 'Мерч-магазины', 'Корпоративные коллекции'],
        },
      ],
    },
    {
      categorySlug: 'longslivy',
      modelId: 'oversize-ls',
      modelTitle: 'Лонгслив оверсайз',
      modelDescription:
        'Свободный крой лонгслива для lifestyle-мерча и бренд-магазинов.',
      options: [
        {
          id: 'ls-os-basic',
          title: 'Лонгслив oversize basic',
          shortDescription: 'Свободный крой для lifestyle-мерча и бренд-магазинов.',
          imageLabel: 'Лонгслив оверсайз basic',
          materialOptions: ['Хлопок меланж', 'Хлопок 100%'],
          densityOptions: ['180 г/м²', '200 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'DTG-печать', 'Шелкография', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Оверсайз-крой с длинным рукавом',
            'Хлопок меланж или 100%, 180–200 г/м²',
            'Удлинённый силуэт',
          ],
          useCases: ['Lifestyle-мерч', 'Молодёжные коллекции', 'Streetwear'],
        },
        {
          id: 'ls-os-premium',
          title: 'Лонгслив oversize premium',
          shortDescription: 'Плотный оверсайз-лонгслив с расширенным брендингом.',
          imageLabel: 'Лонгслив оверсайз premium',
          materialOptions: ['Хлопок меланж', 'Хлопок 100%'],
          densityOptions: ['200 г/м²', '220 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Серый меланж', hex: '#b0b8c1' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Вышивка', 'DTF-печать', 'DTG-печать', 'Шелкография', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотность 200–220 г/м² — премиальная',
            'Свободный и удлинённый крой',
            'Вышивка на рукаве и груди',
          ],
          useCases: ['Премиум lifestyle-мерч', 'Бренд-магазины', 'Коллаборации'],
        },
      ],
    },
    {
      categorySlug: 'longslivy',
      modelId: 'sport-ls',
      modelTitle: 'Спортивный лонгслив',
      modelDescription:
        'Влагоотводящий лонгслив для спортивных команд и активных мероприятий.',
      options: [
        {
          id: 'ls-sport',
          title: 'Спортивный лонгслив',
          shortDescription: 'Влагоотводящая ткань с плоскими швами для активных тренировок.',
          imageLabel: 'Спортивный лонгслив',
          materialOptions: ['Полиэстер 100%', 'Смеска'],
          densityOptions: ['160 г/м²', '180 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'Сублимация', 'Шелкография'],
          printPositions: ['Грудь', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Влагоотводящий полиэстер',
            'Плоские швы без натирания',
            'Плотность 160–180 г/м²',
          ],
          useCases: ['Спортивные тренировки', 'Беговые события', 'Корпоративный спорт'],
        },
        {
          id: 'ls-team',
          title: 'Лонгслив для команды',
          shortDescription: 'Командный лонгслив с местом под номер и имя.',
          imageLabel: 'Лонгслив для команды',
          materialOptions: ['Полиэстер 100%', 'Смеска'],
          densityOptions: ['160 г/м²', '180 г/м²'],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
          ],
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['DTF-печать', 'Сублимация', 'Шелкография'],
          printPositions: ['Грудь', 'Спина (номер)', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Индивидуальные номера и имена',
            'Влагоотводящий полиэстер',
            'Плотность 160–180 г/м²',
          ],
          useCases: ['Хоккейные команды', 'Корпоративные турниры', 'Спортивные школы'],
        },
      ],
    },
    {
      categorySlug: 'longslivy',
      modelId: 'uniform-ls',
      modelTitle: 'Лонгслив для формы',
      modelDescription:
        'Плотный трикотаж для ежедневного использования в форме персонала и корпоративной одежде.',
      options: [
        {
          id: 'ls-personnel',
          title: 'Лонгслив для персонала',
          shortDescription: 'Плотный трикотаж для ежедневного использования в форме персонала.',
          imageLabel: 'Лонгслив для персонала',
          materialOptions: ['Хлопок 100%', 'Смеска'],
          densityOptions: ['180 г/м²', '200 г/м²'],
          colorOptions: BASE_COLORS,
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Хлопок или смеска, 180–200 г/м²',
            'Прямой крой для ежедневной носки',
            'Стойкость к многократным стиркам',
          ],
          useCases: ['Персонал в форме', 'Охрана', 'Технические специалисты'],
        },
        {
          id: 'ls-corporate',
          title: 'Лонгслив под корпоративную форму',
          shortDescription: 'Лонгслив с корпоративными цветами под индивидуальный заказ.',
          imageLabel: 'Лонгслив корпоративный',
          materialOptions: ['Хлопок 100%', 'Смеска'],
          densityOptions: ['180 г/м²', '200 г/м²'],
          colorOptions: BASE_COLORS,
          sizeOptions: STANDARD_SIZES,
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (по центру)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Корпоративные цвета по Pantone',
            'Единый стиль с другой формой',
            'Хлопок или смеска, 180–200 г/м²',
          ],
          useCases: ['Единая корпоративная форма', 'Ритейл и HoReCa', 'Branded одежда'],
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════════════════
  // СУМКИ
  // ═══════════════════════════════════════════════════════════════════════════
  sumki: [
    {
      categorySlug: 'sumki',
      modelId: 'shoppers',
      modelTitle: 'Шопперы',
      modelDescription:
        'Хлопковые шопперы с длинными ручками — популярный промо-носитель для мероприятий и подарков.',
      options: [
        {
          id: 'shopper-220',
          title: 'Шоппер хлопковый 220 г/м²',
          shortDescription: 'Лёгкий экономичный шоппер для большого тиража.',
          imageLabel: 'Шоппер хлопковый 220 г/м²',
          materialOptions: ['Хлопок 220 г/м²'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Лицевая сторона (центр)', 'Лицевая сторона (верх)', 'Обратная сторона'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Хлопок 220 г/м²',
            'Длинные ручки для плеча',
            'Экологичная альтернатива пакету',
          ],
          useCases: ['Промоакции', 'Раздача на мероприятиях', 'Экомерч'],
        },
        {
          id: 'shopper-280',
          title: 'Шоппер хлопковый 280 г/м²',
          shortDescription: 'Плотный шоппер для более долгого использования.',
          imageLabel: 'Шоппер хлопковый 280 г/м²',
          materialOptions: ['Хлопок 280 г/м²'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Лицевая сторона (центр)', 'Лицевая сторона (верх)', 'Обратная сторона'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Плотный хлопок 280 г/м²',
            'Долговечный и прочный',
            'Хорошо держит форму',
          ],
          useCases: ['Корпоративные подарки', 'Welcome-наборы', 'Брендовые шопперы'],
        },
        {
          id: 'shopper-bottom',
          title: 'Шоппер с дном',
          shortDescription: 'Объёмный шоппер с укреплённым дном — вместительный и устойчивый.',
          imageLabel: 'Шоппер с дном',
          materialOptions: ['Хлопок', 'Оксфорд'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Лицевая сторона (центр)', 'Лицевая сторона (верх)', 'Обратная сторона'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Укреплённое дно — больше объём',
            'Хлопок или Оксфорд',
            'Устойчив при наполнении',
          ],
          useCases: ['Продуктовые шопперы', 'Welcome-наборы', 'Корпоративные подарки'],
        },
      ],
    },
    {
      categorySlug: 'sumki',
      modelId: 'backpacks',
      modelTitle: 'Рюкзаки',
      modelDescription:
        'Корпоративные рюкзаки и мешки-рюкзаки для welcome-наборов и мероприятий.',
      options: [
        {
          id: 'backpack-city',
          title: 'Рюкзак городской',
          shortDescription: 'Вместительный рюкзак с карманами для ноутбука — корпоративный подарок.',
          imageLabel: 'Городской корпоративный рюкзак',
          materialOptions: ['Нейлон', 'Оксфорд 210D'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Фронтальный карман', 'Основной отдел (спереди)'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Нейлон или Оксфорд 210D',
            'Карман для ноутбука до 15"',
            'Эргономичные лямки',
          ],
          useCases: ['Корпоративные подарки', 'Welcome-наборы', 'Деловые мероприятия'],
        },
        {
          id: 'backpack-drawstring',
          title: 'Рюкзак-мешок',
          shortDescription: 'Лёгкий мешок с кулиской — экономичный вариант для промо.',
          imageLabel: 'Рюкзак-мешок',
          materialOptions: ['Хлопок', 'Оксфорд'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Центр (лицевая сторона)'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Лёгкий и компактный',
            'Хлопок или Оксфорд',
            'Удобная кулиска',
          ],
          useCases: ['Спортивные мероприятия', 'Промораздача', 'Студенческие кампании'],
        },
      ],
    },
    {
      categorySlug: 'sumki',
      modelId: 'event-bags',
      modelTitle: 'Сумки для мероприятий',
      modelDescription:
        'Поясные и спортивные сумки для активных мероприятий, промо и корпоративных подарков.',
      options: [
        {
          id: 'bag-waist',
          title: 'Поясная сумка',
          shortDescription: 'Компактная поясная сумка для outdoor-мероприятий и фестивалей.',
          imageLabel: 'Поясная сумка',
          materialOptions: ['Нейлон', 'Оксфорд'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Центр (лицевая сторона)'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Нейлон или Оксфорд',
            'Регулируемый пояс',
            'Молния YKK',
          ],
          useCases: ['Фестивали', 'Outdoor-события', 'Спортивные мероприятия'],
        },
        {
          id: 'bag-sport',
          title: 'Спортивная сумка',
          shortDescription: 'Вместительная спортивная сумка с карманами — для команд и наборов.',
          imageLabel: 'Спортивная сумка',
          materialOptions: ['Оксфорд', 'Нейлон'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Фронтальный карман', 'Боковая панель'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Оксфорд или Нейлон',
            'Несколько отделений',
            'Ручки и плечевой ремень',
          ],
          useCases: ['Спортивные команды', 'Корпоративные подарки', 'Welcome-наборы'],
        },
        {
          id: 'bag-welcome',
          title: 'Сумка для welcome-набора',
          shortDescription: 'Брендовая сумка для комплектации welcome-набора.',
          imageLabel: 'Сумка для welcome-набора',
          materialOptions: ['Хлопок', 'Оксфорд'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Бежевый', hex: '#d4b483' },
          ],
          sizeOptions: ['Стандартный размер', 'Малый формат', 'Большой формат', 'Размер по ТЗ'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Вышивка', 'Бирки', 'Шевроны'],
          printPositions: ['Лицевая сторона (центр)', 'Обратная сторона'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Подходит для комплектации набора',
            'Хлопок или Оксфорд',
            'Брендирование по всей плоскости',
          ],
          useCases: ['Welcome-наборы для сотрудников', 'Подарки партнёрам', 'Корпоративные события'],
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════════════════
  // ЖИЛЕТКИ
  // ═══════════════════════════════════════════════════════════════════════════
  zhiletki: [
    {
      categorySlug: 'zhiletki',
      modelId: 'promo-vest',
      modelTitle: 'Промо-жилетки',
      modelDescription:
        'Лёгкие промо-жилетки и сигнальные модели для мероприятий и персонала.',
      options: [
        {
          id: 'vest-promo',
          title: 'Промо-жилетка',
          shortDescription: 'Лёгкая жилетка для мероприятий и выставочного персонала.',
          imageLabel: 'Промо-жилетка',
          materialOptions: ['Оксфорд 210D', 'Полиэстер'],
          densityOptions: [],
          colorOptions: BASE_COLORS,
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (правая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Оксфорд 210D или полиэстер',
            'Лёгкая и компактная',
            'Яркое брендирование',
          ],
          useCases: ['Промо-мероприятия', 'Выставочный персонал', 'Промоутеры'],
        },
        {
          id: 'vest-signal',
          title: 'Сигнальная жилетка',
          shortDescription: 'Флуоресцентная жилетка с световозвращающими полосами.',
          imageLabel: 'Сигнальная жилетка',
          materialOptions: ['Полиэстер сигнальный'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Жёлтый сигнальный', hex: '#f5c518' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (правая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Флуоресцентный материал',
            'Световозвращающие полосы',
            'Соответствует нормам безопасности',
          ],
          useCases: ['Строительные площадки', 'Дорожные работы', 'Склады и логистика'],
        },
      ],
    },
    {
      categorySlug: 'zhiletki',
      modelId: 'personnel-vest',
      modelTitle: 'Жилетки для персонала',
      modelDescription:
        'Прочные рабочие жилетки с карманами для производственного и сервисного персонала.',
      options: [
        {
          id: 'vest-personnel',
          title: 'Жилетка для персонала',
          shortDescription: 'Плотная жилетка для производственного и сервисного персонала.',
          imageLabel: 'Жилетка для персонала',
          materialOptions: ['Оксфорд 420D', 'Оксфорд 210D'],
          densityOptions: [],
          colorOptions: BASE_COLORS,
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (правая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Прочный Оксфорд 420D',
            'Несколько карманов',
            'Устойчив к износу',
          ],
          useCases: ['Производственные компании', 'Склады', 'Торговый персонал'],
        },
        {
          id: 'vest-pockets',
          title: 'Жилетка с карманами',
          shortDescription: 'Максимальное количество карманов для полевых сотрудников.',
          imageLabel: 'Жилетка с карманами',
          materialOptions: ['Оксфорд 420D'],
          densityOptions: [],
          colorOptions: BASE_COLORS,
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (правая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Оксфорд 420D',
            'Множество карманов разного размера',
            'Прочная фурнитура',
          ],
          useCases: ['Охрана', 'Полевые инспекторы', 'Технические службы'],
        },
      ],
    },
    {
      categorySlug: 'zhiletki',
      modelId: 'outdoor-vest',
      modelTitle: 'Outdoor-жилетки',
      modelDescription:
        'Softshell и утеплённые жилетки для активных задач и корпоративной формы.',
      options: [
        {
          id: 'vest-softshell',
          title: 'Софтшелл-жилетка',
          shortDescription: 'Ветро- и водоотталкивающий softshell — для активных задач на улице.',
          imageLabel: 'Жилетка softshell',
          materialOptions: ['Softshell', 'Softshell stretch'],
          densityOptions: [],
          colorOptions: BASE_COLORS,
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (правая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Softshell — ветро- и влагозащита',
            'Стретч-вариант для подвижности',
            'Лёгкая и функциональная',
          ],
          useCases: ['Выездные сотрудники', 'Outdoor-мероприятия', 'Корпоративная форма'],
        },
        {
          id: 'vest-insulated',
          title: 'Утепленная жилетка',
          shortDescription: 'Оксфорд с утеплителем для холодного сезона.',
          imageLabel: 'Утеплённая жилетка',
          materialOptions: ['Оксфорд + утеплитель', 'Нейлон + утеплитель'],
          densityOptions: [],
          colorOptions: BASE_COLORS,
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Грудь (правая)', 'Спина', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Утеплитель 80–150 г',
            'Оксфорд или Нейлон',
            'Для работы в холодных условиях',
          ],
          useCases: ['Зимняя форма', 'Склады и логистика', 'Наружные работы'],
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════════════════
  // КУРТКИ
  // ═══════════════════════════════════════════════════════════════════════════
  kurtki: [
    {
      categorySlug: 'kurtki',
      modelId: 'light-jacket',
      modelTitle: 'Лёгкие куртки',
      modelDescription:
        'Ветровки, бомберы и анораки — для промо, мероприятий и корпоративного мерча.',
      options: [
        {
          id: 'jacket-wind',
          title: 'Ветровка',
          shortDescription: 'Лёгкая ветровка, складывается в мешочек — удобный промо-сувенир.',
          imageLabel: 'Ветровка промо',
          materialOptions: ['Таффета', 'Нейлон'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
            { name: 'Хаки', hex: '#556b2f' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на отдельных элементах', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Таффета или Нейлон',
            'Складывается в чехол',
            'Ветро- и влагозащита',
          ],
          useCases: ['Промоакции', 'Летние мероприятия', 'Командные выходы'],
        },
        {
          id: 'jacket-bomber',
          title: 'Бомбер',
          shortDescription: 'Классический бомбер с рибаной — для lifestyle-мерча и подарков.',
          imageLabel: 'Бомбер корпоративный',
          materialOptions: ['Нейлон', 'Таффета'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
            { name: 'Хаки', hex: '#556b2f' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на отдельных элементах', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Классический силуэт бомбер',
            'Рибана на манжетах и поясе',
            'Нейлон или Таффета',
          ],
          useCases: ['Lifestyle-мерч', 'Корпоративные подарки', 'Бренд-коллекции'],
        },
        {
          id: 'jacket-anorak',
          title: 'Анорак',
          shortDescription: 'Надевается через голову — компактный и практичный для outdoor.',
          imageLabel: 'Анорак',
          materialOptions: ['Нейлон', 'Оксфорд'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
            { name: 'Хаки', hex: '#556b2f' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на отдельных элементах', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Надевается через голову',
            'Нейлон или Оксфорд',
            'Ветро- и водозащита',
          ],
          useCases: ['Outdoor-мероприятия', 'Командные походы', 'Корпоративный мерч'],
        },
      ],
    },
    {
      categorySlug: 'kurtki',
      modelId: 'technical-jacket',
      modelTitle: 'Технические куртки',
      modelDescription:
        'Softshell и полевые куртки для выездных сотрудников и корпоративной формы.',
      options: [
        {
          id: 'jacket-softshell',
          title: 'Куртка softshell',
          shortDescription: 'Функциональная куртка из ветро- и водозащитного softshell.',
          imageLabel: 'Куртка softshell',
          materialOptions: ['Softshell 3 слоя', 'Softshell stretch'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
            { name: 'Хаки', hex: '#556b2f' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на отдельных элементах', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Softshell 3 слоя',
            'Ветро- и влагозащита',
            'Стретч для подвижности',
          ],
          useCases: ['Выездные команды', 'Технические специалисты', 'Корпоративная форма'],
        },
        {
          id: 'jacket-field',
          title: 'Куртка для выездной команды',
          shortDescription: 'Прочная куртка для выездных и полевых задач.',
          imageLabel: 'Полевая куртка',
          materialOptions: ['Оксфорд + флис', 'Таффета + флис'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
            { name: 'Хаки', hex: '#556b2f' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на отдельных элементах', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Оксфорд или Таффета + флис',
            'Прочность для полевых задач',
            'Несколько карманов',
          ],
          useCases: ['Полевые инспекторы', 'Монтажные бригады', 'Корпоративная форма'],
        },
      ],
    },
    {
      categorySlug: 'kurtki',
      modelId: 'warm-jacket',
      modelTitle: 'Утеплённые куртки',
      modelDescription:
        'Тёплые куртки с синтепоном — для холодного сезона и зимних мероприятий.',
      options: [
        {
          id: 'jacket-insulated',
          title: 'Утепленная куртка',
          shortDescription: 'Оксфорд с синтепоном — для работ на улице в холодный сезон.',
          imageLabel: 'Утеплённая куртка',
          materialOptions: ['Оксфорд + синтепон'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
            { name: 'Хаки', hex: '#556b2f' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на отдельных элементах', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Оксфорд + синтепон 150–200 г',
            'Тепло до -10°C',
            'Ветро- и влагозащита',
          ],
          useCases: ['Зимняя форма', 'Уличные мероприятия', 'Наружные работы'],
        },
        {
          id: 'jacket-winter',
          title: 'Зимняя корпоративная куртка',
          shortDescription: 'Тёплая зимняя куртка для корпоративной формы.',
          imageLabel: 'Зимняя корпоративная куртка',
          materialOptions: ['Оксфорд + утеплитель 200 г'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Графит', hex: '#374151' },
            { name: 'Хаки', hex: '#556b2f' },
          ],
          sizeOptions: VEST_JACKET_SIZES,
          brandingOptions: ['Вышивка', 'Шевроны', 'DTF-печать', 'Тиснение на отдельных элементах', 'Бирки'],
          printPositions: ['Грудь (левая)', 'Спина', 'Рукав', 'Воротник'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Утеплитель 200 г — для морозов',
            'Оксфорд с водоотталкивающей пропиткой',
            'Фурнитура YKK',
          ],
          useCases: ['Корпоративная зимняя форма', 'Охранные структуры', 'Уличный персонал'],
        },
      ],
    },
  ],

  // ═══════════════════════════════════════════════════════════════════════════
  // ДОЖДЕВИКИ
  // ═══════════════════════════════════════════════════════════════════════════
  dozhdeviki: [
    {
      categorySlug: 'dozhdeviki',
      modelId: 'poncho-rain',
      modelTitle: 'Дождевики-пончо',
      modelDescription:
        'Пончо из PEVA — самый экономичный вариант для массовой промо-раздачи и фестивалей.',
      options: [
        {
          id: 'rain-poncho-basic',
          title: 'Дождевик-пончо basic',
          shortDescription: 'Не требует подгонки по размеру, быстро надевается.',
          imageLabel: 'Дождевик-пончо basic',
          materialOptions: ['PEVA 60 мкм', 'PEVA 80 мкм'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: ['Один размер (пончо)', 'S/M', 'M/L', 'L/XL'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Термотрансфер', 'Шевроны'],
          printPositions: ['Спина', 'Грудь', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'PEVA 60–80 мкм',
            'Универсальный размер',
            'Компактно складывается',
          ],
          useCases: ['Промораздача', 'Фестивали', 'Массовые мероприятия'],
        },
        {
          id: 'rain-poncho-festival',
          title: 'Фестивальный дождевик-пончо',
          shortDescription: 'Яркий плотный пончо — максимальная видимость в толпе.',
          imageLabel: 'Фестивальный дождевик-пончо',
          materialOptions: ['PEVA 80 мкм', 'Нейлон'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: ['Один размер (пончо)', 'S/M', 'M/L', 'L/XL'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Термотрансфер', 'Шевроны'],
          printPositions: ['Спина', 'Грудь', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'PEVA 80 мкм или Нейлон',
            'Яркие фестивальные цвета',
            'Брендирование на всю спину',
          ],
          useCases: ['Фестивали', 'Открытые мероприятия', 'Промо-кампании'],
        },
      ],
    },
    {
      categorySlug: 'dozhdeviki',
      modelId: 'jacket-rain',
      modelTitle: 'Дождевики-куртки',
      modelDescription:
        'Структурированные дождевики с кнопками или молниями — для промо-команд.',
      options: [
        {
          id: 'rain-buttons',
          title: 'Дождевик на кнопках',
          shortDescription: 'Кнопки по бокам для лучшей фиксации и регулировки объёма.',
          imageLabel: 'Дождевик на кнопках',
          materialOptions: ['PEVA', 'Нейлон Taffe'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: ['Один размер (пончо)', 'S/M', 'M/L', 'L/XL'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Термотрансфер', 'Шевроны'],
          printPositions: ['Спина', 'Грудь', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'PEVA или Нейлон Taffe',
            'Кнопочная застёжка по бокам',
            'Лучше сидит, чем пончо',
          ],
          useCases: ['Промо-команды', 'Мероприятия на улице', 'Спонсорский мерч'],
        },
        {
          id: 'rain-promo',
          title: 'Промо-дождевик',
          shortDescription: 'Лёгкий Ripstop-дождевик для спонсорских мероприятий.',
          imageLabel: 'Промо-дождевик',
          materialOptions: ['Полиэстер Ripstop', 'Нейлон'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: ['Один размер (пончо)', 'S/M', 'M/L', 'L/XL'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Термотрансфер', 'Шевроны'],
          printPositions: ['Спина', 'Грудь', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Ripstop — прочная и лёгкая ткань',
            'Большая площадь для логотипа',
            'Яркие промо-цвета',
          ],
          useCases: ['Спонсорские мероприятия', 'Марафоны', 'Гонки'],
        },
      ],
    },
    {
      categorySlug: 'dozhdeviki',
      modelId: 'special-rain',
      modelTitle: 'Специальные дождевики',
      modelDescription:
        'Дождевики в индивидуальной упаковке и для промо-команд — особые форматы.',
      options: [
        {
          id: 'rain-individual-pack',
          title: 'Дождевик в индивидуальной упаковке',
          shortDescription: 'Компактная упаковка в чехол или поясная сумочка — удобная раздатка.',
          imageLabel: 'Дождевик в индивидуальной упаковке',
          materialOptions: ['PEVA 80 мкм', 'Нейлон'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: ['Один размер (пончо)', 'S/M', 'M/L', 'L/XL'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Термотрансфер', 'Шевроны'],
          printPositions: ['Спина', 'Грудь', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'PEVA 80 мкм или Нейлон',
            'Индивидуальная упаковка-чехол',
            'Брендирование на чехле',
          ],
          useCases: ['Welcome-наборы', 'Корпоративные подарки', 'Туристические бюро'],
        },
        {
          id: 'rain-promo-team',
          title: 'Дождевик для промо-команды',
          shortDescription: 'Единый стиль для всей команды на outdoor-мероприятии.',
          imageLabel: 'Дождевик для промо-команды',
          materialOptions: ['Нейлон', 'Полиэстер'],
          densityOptions: [],
          colorOptions: [
            ...BASE_COLORS,
            { name: 'Оранжевый', hex: '#f97316' },
            { name: 'Зелёный', hex: '#16a34a' },
          ],
          sizeOptions: ['Один размер (пончо)', 'S/M', 'M/L', 'L/XL'],
          brandingOptions: ['Шелкография', 'DTF-печать', 'Термотрансфер', 'Шевроны'],
          printPositions: ['Спина', 'Грудь', 'Рукав'],
          quantityOptions: STANDARD_QTY,
          priceFactors: STANDARD_PRICE_FACTORS,
          characteristics: [
            'Нейлон или полиэстер',
            'Единый стиль команды',
            'Большое поле для логотипа на спине',
          ],
          useCases: ['Промо-команды', 'Спонсорские акции', 'Фестивальный персонал'],
        },
      ],
    },
  ],
};
